### ISSUE TITLE
Interfaces cannot extend multiple interfaces

### ISSUE THREAD

**Issue by UFOMelkor** [phpmetrics/PhpMetrics#116]
Actualy a class can have only one parent (correct), but an interface can also have only one parent (incorrect).

Because ReflectedInterface inherits ReflectedClass, this would need some refactorings. I'd like to remove most calls of `getParent()` and return the parent class within `getDependencies()`. Thereby we're more flexible and can handle interfaces that extends multiple interfaces.

Any thoughts? @Halleck45

**Comment by Halleck45** [comment]
Yes, you're right... This should be fixed

**Comment by Halleck45** [comment]
I think this issue is outdated. I close it
