### ISSUE TITLE
CakePHP3 does not seem to work

### ISSUE THREAD

**Issue by dereuromark** [phpmetrics/PhpMetrics#155]
Maintainability.................... 67.71 / 100
Accessibility for new developers...    50 / 100
Simplicity of algorithms...........     0 / 100
Volume.............................     0 / 100
Reducing bug's probability.........     0 / 100

**Comment by Halleck45** [comment]
Hi,

hum, looking in source code (v3.2), score is coherent:

+ Bugs by file: 0.91 (good: < 0.07)
+ Complexity cyclomatic (average) : 17,89 (good: < 2)

And all other indicators are same. I suggest to read the HTML report to see details.

But, indeed, 0 is maybe... a bit naughty. Formula should be improved.
