### ISSUE TITLE
Creation of PhpMetrics organization

### ISSUE THREAD

**Issue by Halleck45** [phpmetrics/PhpMetrics#156]
Hi, 

I would like to create an organization for PhpMetrics :

+ I need help to improve and maintain this tool
+ I think that this tool should be more "open" 
+ I need advice to improve the tool, I must not decide alone

I don't know how to plan the changes. Maybe:

- [x] creation of [organization](https://github.com/orgs/phpmetrics)
- [x] creation of [gitter room](https://gitter.im/phpmetrics)
- [x] ask for help to main contributors
- [ ] imagine a workflow for release mastering, tagging and contributing strategy
- [x] fix all opened bugs
- [x] announcing depreciation of repository ?
- [x] updating composer.json
- [x] migrate code to new repository
- [x] migrate website to [new repository](https://github.com/phpmetrics/website)
- [x] change DNS to phpmetrics.github.io 

What do you think about this roadmap ? 

@fonsecas72, @UFOMelkor, I appreciate your help. Do you want to integrate PhpMetrics organization as release masters ?

Thanks

**Comment by fonsecas72** [comment]
Hi, yeah I would like that. Let's do it!

**Comment by UFOMelkor** [comment]
Yesterday I was just thinking about me doing more open source stuff again. So it's like a perfect timing. I would be glad to help.

**Comment by Halleck45** [comment]
@UFOMelkor @fonsecas72 Nice ! See you on [https://gitter.im/phpmetrics][gitter]
