### ISSUE TITLE
Problem with ,,big'' php files.

### ISSUE THREAD

**Issue by Setitch** [phpmetrics/PhpMetrics#170]
File https://github.com/phpWhois/idna-convert/blob/master/idna_convert.class.php cannot be checked as its too big. (Memory limit is 1Gb, but still some files are not parsable). Is there a way of fixing it?

**Comment by fonsecas72** [comment]
Can you try with the latest version? I couldn't replicate this.

**Comment by Halleck45** [comment]
@Setitch Does the problem persist ?

**Comment by Setitch** [comment]
I think it works now, however on some system im forced to use older php version hence php 5.3 version, and the problem is still under that version.

**Comment by Halleck45** [comment]
Ok. I close this issue ...
