### ISSUE TITLE
Incompatibilities with PhpMetrics and Laravel 5.* helpers

### ISSUE THREAD

**Issue by crapougnax** [phpmetrics/PhpMetrics#172]
Some hoa packages used by PhpMetrics declare the same helpers functions name than Laravel 5. This leads to inconsistencies and sometimes exceptions.

**Comment by fonsecas72** [comment]
I couldn't replicate this. 
Can you give us more information, starting with the command that you tried to run?

**Comment by Halleck45** [comment]
@crapougnax Can you provide more details please ?

**Comment by crapougnax** [comment]
Yep, as soon as I can reproduce on a clean install.

Olivier Lépine
Quatrain Technologies
8 rue de la Petite Meuse
84000 Avignon
Tél. 04 90 80 40 40

**Comment by Halleck45** [comment]
ping @crapougnax 

I cannot reproduce:

```
git clone git@github.com:laravel/laravel.git laravel
phpmetrics laravel --failure-condition="sum.loc > 10000"
```

> I don't get any error

**Comment by crapougnax** [comment]
My bad. The issue was related to the halleck45/phpmetrics package.

We removed phpmetrics from our require-dev because there was a conflit between two declaration of the url() helper function.

Tried to reproduce but base code has widely evolved.

thanks for your help.
