### ISSUE TITLE
PHP5.4 dropping

### ISSUE THREAD

**Issue by Hywan** [phpmetrics/PhpMetrics#173]
Hello :-),

Are you planning to drop PHP5.4?

**Comment by fonsecas72** [comment]
Hi, it should be dropped at some point :-)
It's not clear to me why you're asking. Is it because of hoa/ruler?

**Comment by Halleck45** [comment]
Hi,

PHP 5.4 still used by 5% of users today. Supporting  PHP 5.4 is not a problem for PhpMetrics.

Why do you want to drop PHP 5.4 ?

**Comment by Hywan** [comment]
@Halleck45 @fonsecas72 Mainly because you will be able to use `hoa/ruler` `~2.0` ;-).

**Comment by Halleck45** [comment]
@Hywan that's an idea :)

As long as the support PHP 5.4 still easy for us, I think we will try to keep PHP 5.4 ... But maybe I'm too "old school" :/

**Comment by Hywan** [comment]
It's up to you to decide. I am not here to troll :-). You can keep this issue open as a gently reminder.

**Comment by Halleck45** [comment]
Do not hesitate to reopen this issue if you think that we made a mistake.

**Comment by Hywan** [comment]
@Halleck45 Everything is fine!

**Comment by Hywan** [comment]
@Halleck45 Just keep in mind that hoa/ruler is now on `~2.0`.
