### ISSUE TITLE
PHPMetrics. High LCOM on Utils classes

### ISSUE THREAD

**Issue by Csardelacal** [phpmetrics/PhpMetrics#175]
Hello!

I must admit that I'm absolutely in love with phpmetrics and that it's a tool that's become invaluable to me.

One thing bugs me though. I have a string utils class in my software. Basically an abstract class that contains 9 static methods that are expected to help with string operations. One converts strings into their URL friendly counter parts, one converts camel case names into under_score_names and so on.

```php
<?php

abstract class StringUtils {

   public static function endsWith($haystack, $needle) { /*Method body*/}
  /* 8 More methods */
}
```

My issue is that a class that is abstract and contains only static methods is marked as having an extremely high LCOM value. Which would be arguably incorrect, since they all operate on strings.

I could, of course, replace the class with one that looks like this:

```php
<?php

class String {
   private $str;

   public function __construct($str) { $this->str = $str; }

   public function endsWith($str) { /*Method body*/}
  /** 8 more methods **/
}
```

But it doesn't really look like that much better a practice to me personally. Specially considering the fact that the code you would have to write to invoke the second method would become a little literary adventure - and it would have some memory overhead due to the fact that we're creating a ton of objects.

**Comment by fonsecas72** [comment]
Interesting question. AFAIK the LCOM metrics can be easily be tricked, not only for simple helpers with static methods but also for example with getters and setters. For some, it is somehow a controversial metric because of such fragility.
I usually ignore this kind of metrics for those kind of classes.
I don't think we have much to do from PHPMetrics side. 
Do you have any ideas?

**Comment by Halleck45** [comment]
Hi,

I'll try to provide a response with my poor english :/

Your class is a "collection of functions". Having a high LCOM here is normal. In a object oriented world, your class could be replaced by functions:

```php
namespace String;

function endsWith($str, $needle) {}
(...)
```

```php
// example
String\endsWith('abd', 'def');
```

If you want to follow SOLID conventions, **yes, your class `String` should represent a string** (ObjectValue pattern) and be immutable. So, yes, your second example should be prefered in a object oriented world:

```php
<?php

class String {
   private $str;

   public function __construct($str) { $this->str = $str; }

   public function endsWith($str) { /*Method body*/}
  /** 8 more methods **/
}
```

Remember: an **abstract** class is **not a class that can't be instancied** (it is a consequence). No, an abstract class is a class that **must be specialized** (have a children).

**Comment by Csardelacal** [comment]
It seems to me that rather than a necessary thing. It's become an industry standard for PHP applications to use Util classes that wrap several functions into a class.

Sorry, I didn't mean Abstract either. But a class with a private __construct method.

Even Sensiolabs Insights recommends the behavior. When introducing a global function they will point it out and tell you to put it into a class with static methods.

My problem right now with using a String object is that I'll have to call getContent() whenever I feel like calling a method from an external library that doesn't implement my class and create a new String() every time they return me something.

A simple ``` $b = Library::fn($a) ``` will become a monster like ```$b = new StringHelper(Library::fn($a->getContent())``` which only looks remotely clean when it's one assignment.

While I agree that it's not an easy fix I would suggest that classes with a private constructor and only static methods are treated as a collection of functions (Utils) class and are kinda ignored in this situation.

* Maybe an option would be to have an option to leave Utils alone when calculating these values. 
* Maybe an @annotation that we can add in the Doc blocks of classes and functions that reports those as being irrelevant.

The second option would also provide a way to mark getters and setters that always screw up the LCOM too. Something like this:

```php
<?php

/**
 * @UtilityClass
 **/
class StringUtils {
  private __construct() {}
  static function endsWith($string) {}
  static function startsWith($string) {}
}

class WithGetters
{

  private $a;
  private $b;

  public function __construct($a, $b) {/*Method body*/}

  /**
   * @attribute-getter
   */
  public function getA() { return $this->a; }

  public function calculate() { return $this->a + $this->b; }
}
```

As far as I know, these classes would both be reported as an LCOM > 1 since they provide different endpoints. The attributes could be used to report to PHPMetrics that these classes have some alternative measurements.

< opinion > I personally feel like they're not making any of the features in PHPmetrics less interesting. Furthermore, the software has helped me to look at my code in a more critical way and it helps me detect spots where I could be improving.

That makes me the first person interested in getting told what I'm doing wrong and improve. But false positives kinda make everything "go red" and therefore ruin the experience. </ opinion >

**Comment by Halleck45** [comment]
The `String` class is not a solution in PHP. It was just an example :)

Getters and setters [are not considered](https://github.com/Halleck45/PhpMetrics/blob/master/src/Hal/Metrics/Complexity/Structural/LCOM/LackOfCohesionOfMethods.php#L43) in LCOM calculation

> I would suggest that classes with a private constructor and only static methods are treated as a collection of functions (Utils) class and are kinda ignored in this situation

According to me (so it's only my opinion), if you need to have a collection of functions, do not create class, and do not put them in the global namespace: create your own namespace.

LCOM doesn't care about the function/role of class. LCOM is **just** a metric. 

Today, I want that PhpMetrics give only pure metrics. Not "metric about controller in sf2 application", or "metric about Util class in Wordpress application". May be, in the future, we'll integrate plugins to PhpMetrics.  

Meanwhile, you can try to rely the **pattern** of the given class (using [DesignPatternDetector](https://github.com/Halleck45/DesignPatternDetector) to LCOM).

**Comment by UFOMelkor** [comment]
> That makes me the first person interested in getting told what I'm doing wrong and improve. But false positives kinda make everything "go red" and therefore ruin the experience.

I think metrics do not tell you what is wrong and what is true, they just measure your code. To decide, what needs to be improved is kind of a developers job. Perhaps we need another tool that works on top of the metrics collected by PhpMetrics.

**Comment by Halleck45** [comment]
@UFOMelkor You're right. I've just speak about this idea: external plugins, for frameworks, tools, recommandations, pattern detection...

**Comment by Halleck45** [comment]
@Csardelacal can I close this issue ?

**Comment by Csardelacal** [comment]
@Halleck45 I think you can do so. I totally see your points, and I understand where you're coming from. I'll report back if I find more bugs ^^
