### ISSUE TITLE
[LogicException] No file found

### ISSUE THREAD

**Issue by Everyways** [phpmetrics/PhpMetrics#176]
Yop,

Fail to launch PhpMetrics (windows local machine). Everytime it returns No file found.

Ok on linux

Any idea ?

**Comment by Halleck45** [comment]
Hi,

can you provide:

+ the version of phpmetrics
+ your current path
+ the analyzed directory (full path)
+ your OS

Thanks !

**Comment by Halleck45** [comment]
Hi,

can you provide:

+ the version of phpmetrics
+ your current path
+ the analyzed directory (full path)
+ your OS

Thanks !

**Comment by Everyways** [comment]
Hi,

My path is based on a ubuntu based servor I access via shfs (completly available from windows explorer) : G:\myMountpath\rep1\rep2\rep3\my-project\my_path
I lauch phpmetrics from Windows 7 (64bits)
How I get the phpmetrics version ?

**Comment by UFOMelkor** [comment]
`phpmetrics --version`

**Comment by Halleck45** [comment]
ping @Everyways 

And do you have any space char in your local path ?

**Comment by Halleck45** [comment]
I close this issue. @Everyways if the problem persists, do not hesitate to reopen it

**Comment by schmunk42** [comment]
I have similar issues with like all folders **beside `src`** from [my project](https://github.com/phundament/app)

```
root@880a447f61f4:/app# php src/phpmetrics.phar -v vendor/yiisoft/yii2/helpers
PHPMetrics by Jean-François Lépine <https://twitter.com/Halleck45>


                    
  [LogicException]  
  No file found     
                    

Exception trace:
 () at phar:///app/src/phpmetrics.phar/src/Hal/Application/Command/Job/DoAnalyze.php:96
 Hal\Application\Command\Job\DoAnalyze->execute() at phar:///app/src/phpmetrics.phar/src/Hal/Application/Command/Job/Queue.php:51
 Hal\Application\Command\Job\Queue->execute() at phar:///app/src/phpmetrics.phar/src/Hal/Application/Command/RunMetricsCommand.php:128
 Hal\Application\Command\RunMetricsCommand->execute() at phar:///app/src/phpmetrics.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///app/src/phpmetrics.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///app/src/phpmetrics.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///app/src/phpmetrics.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at /app/src/phpmetrics.phar:17

metrics [--report-html REPORT-HTML] [--report-xml REPORT-XML] [--report-cli] [--violations-xml VIOLATIONS-XML] [--report-csv REPORT-CSV] [--report-json REPORT-JSON] [--chart-bubbles CHART-BUBBLES] [--level LEVEL] [--extensions EXTENSIONS] [--excluded-dirs EXCLUDED-DIRS] [--symlinks] [--without-oop] [--ignore-errors] [--failure-condition FAILURE-CONDITION] [--config CONFIG] [--template-title TEMPLATE-TITLE] [--offline] [--] [<path>]
```

But I can pick a single file from there?!

```
root@880a447f61f4:/app# php src/phpmetrics.phar -v vendor/yiisoft/yii2/helpers/ArrayHelper.php 
PHPMetrics by Jean-François Lépine <https://twitter.com/Halleck45>

                                                                               
Maintainability....................   100 / 100
Accessibility for new developers...   100 / 100
Simplicity of algorithms...........   100 / 100
Volume.............................   100 / 100
Reducing bug's probability.........   100 / 100

done
```

Tried with 1.8 and 1.9.2

```
root@880a447f61f4:/app# php src/phpmetrics.phar --version                     
PhpMetrics, by Jean-François Lépine (https://twitter.com/Halleck45) version v1.9.2
```

I also tried with `--symlinks` and I am running everything inside a Docker container.

**Comment by UFOMelkor** [comment]
`vendor` is one of the [directories excluded by default](https://github.com/phpmetrics/PhpMetrics/blob/cb5cdc6f6cd6eb5e6661cbdd00e17ed57fa3e578/src/Hal/Application/Config/TreeBuilder.php#L48). Passing another value as option should solve your problem.

**Comment by schmunk42** [comment]
@UFOMelkor Thank you very much!

These two workarounds worked for me:

    phpmetrics --excluded-dirs=_none_ vendor/mynamespace

or

    cd vendor/mynamespace && phpmetrics .
