### ISSUE TITLE
Travis CI and Scrutinizer not checked after renaming

### ISSUE THREAD

**Issue by skors** [phpmetrics/PhpMetrics#181]
Hi,

there is no project on travis ci for phpmetrics after renaming to the new organization. Also checks aren't run after pushing to branches/pull requests.

**Comment by Halleck45** [comment]
Not fixed, but #2560293 had be merge before i(n order to change configuration in Travis and Packagist).

**Comment by Halleck45** [comment]
Fixed (You can see it in action at [#183](https://github.com/phpmetrics/PhpMetrics/pull/183)).

Thanks for your report :clap:
