### ISSUE TITLE
[Enhancement] Better Relations Map

### ISSUE THREAD

**Issue by YuraLukashik** [phpmetrics/PhpMetrics#186]
Hi
It seems like relations map becomes useless(hard to understand) on projects with a large number of classes.
<img width="947" alt="screen shot 2016-02-20 at 4 03 31 am" src="https://cloud.githubusercontent.com/assets/4070636/13193279/f53c5a38-d786-11e5-850c-2483ca74447e.png">
I guess there is a better representation of such data, like a draggable directed graph or something else.
So, if it seems interesting and people feels discomfort with relations map(like me), then i could provide a PR with suggestions.

**Comment by YuraLukashik** [comment]
@Halleck45 @fonsecas72 ping

**Comment by fonsecas72** [comment]
I tend to agree with you. Different kind of relations graph will give you different feedback though.
If you are willing to do it, I would help the best way possible.

**Comment by theofidry** [comment]
Maybe it would be useful to have a graph to see the relations between "packages" too, to have a more macro view of the relationships.

**Comment by Halleck45** [comment]
@YuraLukashik @fonsecas72 @theofidry Do you want to open a PR on this subject ? I'm not an expert with D3JS...

**Comment by theofidry** [comment]
@Halleck45 I would love to but I'm afraid I lack too much time already and I never used D3JS :p

**Comment by YuraLukashik** [comment]
@Halleck45 I am gonna do that soon

**Comment by Halleck45** [comment]
@YuraLukashik Did you have time to work on this feature ?

**Comment by YuraLukashik** [comment]
@Halleck45 yes, but not enough, I'll try to finish it soon :)

**Comment by theofidry** [comment]
Worth to look into: https://github.com/mamuz/PhpDependencyAnalysis

The graphs are kind of gross, but still nice to use.

**Comment by YuraLukashik** [comment]
hi there
t

**Comment by YuraLukashik** [comment]
sorry, accidentally pressed the button.
I had tried different variants, but haven't found convenient design.
@theofidry PhpDependencyAnalysis looks good, but I don't like them design too, it's hard to navigate there.
is there anyone who could help me with the design of graph?

**Comment by theofidry** [comment]
@YuraLukashik pretty sure you could have a d3.js reporter instead. The generated graph shouldn't be dependent on the renderer anyway, so be it d3.js or another it's "just" a matter of having the appropriate reporter.

Will check in the week if I can help for the design, but I definitely won't have time to help with the code unfortunately :(

**Comment by Halleck45** [comment]
I close this old issue. @theofidry feel free to reopen it if you need :)
