### ISSUE TITLE
Migrating from PHP5.4 to PHP7.0

### ISSUE THREAD

**Issue by feyazbeck** [phpmetrics/PhpMetrics#187]
Hello Guys, 

Is there a way or a tool to scan the code we have that is running to under PHP 5.4 and 5.5 to identify all the functions that will not work under PHP7.0 instead of doing this manually. 

Thank you, 
FEY

**Comment by UFOMelkor** [comment]
Do you mean something like [sstalle/php7cc](https://github.com/sstalle/php7cc)?

**Comment by feyazbeck** [comment]
yes. thanks. I just installed it but it hogging my server memory:

PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 32 bytes) in /root/.composer/vendor/sstalle/php7cc/src/Token/TokenCollection.php


<https://www.callbox.me>

On Feb 27, 2016, at 8:22 PM, Oskar Bley <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you mean something like sstalle/php7cc<https://github.com/sstalle/php7cc>?

**Comment by YuraLukashik** [comment]
@feyazbeck i guess this question is not related to php metrics :)
try to increase the php memory limit [http://php.net/manual/en/ini.core.php#ini.memory-limit](url)
:)

**Comment by infectormp** [comment]
@feyazbeck try https://github.com/wapmorgan/PhpCodeFixer

**Comment by Halleck45** [comment]
Hi,

That's an idea, but PhpMetrics is just a static analyser. This issue is not related to PhpMetrics.

I close this issue
