### ISSUE TITLE
Compatibility with Sf3 project

### ISSUE THREAD

**Issue by llaumgui** [phpmetrics/PhpMetrics#192]
Hi,

is it possible to use a dependacy like: 
~~~
 "symfony/yaml": "~2.3|~3.0"
~~~

To be compatible with a Sf3 project ?

Thx.

**Comment by theofidry** [comment]
:+1:

**Comment by Halleck45** [comment]
Why do you think about #197 ?

**Comment by Halleck45** [comment]
I close this issue. Feel free to continue discussion in #197
