### ISSUE TITLE
Use CDNs for JavaScript dependencies (d3, nvd3...)

### ISSUE THREAD

**Issue by viruzzo** [phpmetrics/PhpMetrics#194]
It would be nice if the JS dependencies for the HTML report were (possibly as an option) included from an external CDN (i.e. https://cdnjs.com/) instead of being incorporated in the file, reducing the size of the generated file.
This would also help towards using a module loader, easing up on the performance for each section.

**Comment by theofidry** [comment]
But it would be nice to have a fallback still, it's nice to be able to run this tool offline...

**Comment by viruzzo** [comment]
Agreed, hence the _possibly as an option_ bit. It needn't even be the default, though IMO offline is the least common use case (might be wrong).

**Comment by Halleck45** [comment]
Done with #199 :)
