### ISSUE TITLE
Lost CSS ans JS on Jenkins

### ISSUE THREAD

**Issue by amelaye** [phpmetrics/PhpMetrics#195]
Hi,
My issue is only with Jenkins, when I make a build, I have no CSS and JS working on the HTML result.
When I realize my report independally, my CSS and JS work perfectely. 
Do you see where the issue is ?
Thanks.

**Comment by Halleck45** [comment]
Hi,

Probably a problem with Jenkins and restrictions about loading scripts on HTML files in workspaces.

Try to run Jenkins with `-Dhudson.model.DirectoryBrowserSupport.CSP=""` (described [here](https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy)).

I don"t think that this issue concerns phpMetrics. I close this issue, feel free to reopen it if your problem persists.
