### ISSUE TITLE
Cyclomatic complexity question

### ISSUE THREAD

**Issue by marcEbury** [phpmetrics/PhpMetrics#200]
Cyclomatic complexity is presented as per file, rather then per method, is this intentionally, as far as i am concerned Cyclomatic complexity is only measured per method, and it seems that phpmetrics is summing up per file, which would be incorrect.

**Comment by Halleck45** [comment]
Hi @marcEbury ,

A class hasn't any decision point. Only methods can indeed have cyclomatic complexity number. But most softwares provide the sum of ccn of methods for one class, and generally call this metric "cyclomatic complexity of class X" ([example for SonarCube](http://www.sonarqube.org/discussing-cyclomatic-complexity/), [example for JHawk](http://www.virtualmachinery.com/jhawkmetricslist.htm)...)

JHawk call this metric "Total Cyclomatic Complexity". For simplicity, I prefer to call it "Cyclomatic complexity", given this number is associated in reports to classes.

**Comment by Halleck45** [comment]
I close this issue. Feel free to reopen it if fou want to continue our discussion :)
