### ISSUE TITLE
Mark old composer packages as abandoned

### ISSUE THREAD

**Issue by UFOMelkor** [phpmetrics/PhpMetrics#201]
Regarding to [#198](https://github.com/phpmetrics/PhpMetrics/issues/198#issuecomment-197766060) and [#189](https://github.com/phpmetrics/PhpMetrics/issues/189#issuecomment-198269314) user do not get the current version of phpmetrics because the packages [`halleck45/phpmetrics`](https://packagist.org/packages/halleck45/phpmetrics) and [`halleck45/php-metrics`](https://packagist.org/packages/halleck45/php-metrics) are still at version v1.8.3 (both packages reference to `https://github.com/Halleck45/PhpMetrics.git`).

Instead of changing the repository of both packages we may consider to abandon the packages.

See composer/composer#3325 for an example how the error message would look.

**Comment by pavarnos** [comment]
+1 just wasted half an hour trying to upgrade the wrong package...

**Comment by Halleck45** [comment]
Yes, I'm totally agree. But how ?

+ repository `Halleck45/PhpMetrics` is transfered to`PhpMetrics/PhpMetrics`. 
+ transfer is necessary if we want that PHAR installation with old URL continue to work.
+ if we want to change the `composer.json` of `Halleck45/PhpMetrics` repository, I need to recreate this repository. Transfers from old Phar URL will not be made.

Do you have any idea / suggest ?

**Comment by UFOMelkor** [comment]
I guess you can use the GUI of packagist. There should be a “Abandon” button available for you at https://packagist.org/packages/halleck45/phpmetrics

**Comment by Halleck45** [comment]
I've looked in packagist.org, and there is a "Edit" button.

So I've changed the GIT repository of "halleck45/phpmetrics" to the new one.

**We can continue to install phpmetrics with both commands**:

+ `composer require halleck45/phpmetrics`
+ `composer require phpmetrics/phpmetrics`

So I think that this issue is fixed (not definitively: we must create a "PhpMetricsDeprecated" repository hosting `halleck45/phpmetrics` and annoucing depreciation of this package).

Meanwhile, I close this issue. Feel free to reopen it if you have any problem

**Comment by UFOMelkor** [comment]
https://packagist.org/packages/halleck45/phpmetrics/abandon does not work?

**Comment by Halleck45** [comment]
I was afraid we could not install an abandoned package.

`halleck45/phpmetrics` is now abandoned. @UFOMelkor @pavarnos Can you make some tests ?

Thanks for your help

**Comment by pavarnos** [comment]
installing halleck45/phpmetrics actually installs phpmetrics/phpmetrics with the latest version.
```
stevep$ composer global require halleck45/phpmetrics
Changed current directory to /Users/stevep/.composer
Using version ^1.9 for halleck45/phpmetrics
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing phpmetrics/phpmetrics (v1.9.1)
  - Installing phpmetrics/phpmetrics (v1.9.2)
    Downloading: 100%         

Writing lock file
Generating autoload files
```

looks like the right thing is happening.

on packagist.org
- halleck45/phpmetrics is marked as abandoned
- halleck45/php-metrics is still valid (maybe should be abandoned too?)

**Comment by Halleck45** [comment]
Cool. I've also abandonned `halleck45/phpmetrics`.

Do you think that I can close this issue ?

**Comment by pavarnos** [comment]
yes. looking good to me (just checked packagist.org: halleck45/php-metrics is marked as abandoned). thanks for all you have done.

**Comment by mablae** [comment]
Looks fine. I also stumbled across the abandoned packages. This is how it should be done! Close it! ;-)

**Comment by Halleck45** [comment]
Cool. I close this issue. Thanks for your help :+1:
