### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by SmetDenis** [phpmetrics/PhpMetrics#205]
Hi,

It seems i have found tiny typo here
http://www.phpmetrics.org/documentation/index.html

![image](https://cloud.githubusercontent.com/assets/1118678/13907018/bb61aabc-ef0e-11e5-9a70-763bb1476e06.png)

Thanks and best regards, Denis.

**Comment by Halleck45** [comment]
Fixed with [this commit](https://github.com/phpmetrics/website/commit/6cbf2baf6a68d9eb25be7308d341f35608bd37bd).

Thanks for your help @theofidry !
