### ISSUE TITLE
Check for Graphviz before Analysis

### ISSUE THREAD

**Issue by mablae** [phpmetrics/PhpMetrics#210]
Hi,

I've installed PhpMetrics version v1.9.2 with composer as require-dev locally.

When I run the analysis the tool analyzes fine, but when it comes to SVG creation, it notices that graphviz is missing. This is/was correct, I installed it and everything went fine. 

It would be great to check graphviz installation BEFORE running the analysis

**Comment by Halleck45** [comment]
Hi,

That's a good idea.

Done with #211
