### ISSUE TITLE
HTTPS fail to load external resources

### ISSUE THREAD

**Issue by neissa** [phpmetrics/PhpMetrics#217]
Hi,
I've installed PhpMetrics v1.10.0 with composer and use the archive.

In the repport we have external ressource loaded with http

http://nvd3.org/assets/js/nv.d3.js
http://d3js.org/d3.v3.min.js
http://nvd3.org/assets/css/nv.d3.css

when the repport is loaded over HTTPS this resources can't load because of mixed origin,

you should use an another CDN like this one  https://cdnjs.com/libraries/nvd3

**Comment by halfer** [comment]
I believe there is a switch in the new version to use local resources rather than CDNs - will that help you out in the short term?

**Comment by Halleck45** [comment]
the  https://cdnjs.com/libraries/nvd3 CDN doesn't contain our used version of nvd3 :(

Using the `--offline` option should resolve your problem. I close this issue, but feel free to reopen it if the problem persists.
