### ISSUE TITLE
Cannot get report for files in directory.

### ISSUE THREAD

**Issue by maxbogus** [phpmetrics/PhpMetrics#218]
Hi,

I've installed PhpMetrics v1.10.0 1.0.2.

When I run this command:

phpmetrics --report-html=myreport.html -- /Users/maksimboguslavsky/repositaries/bankiru_auto_tests/

I get this output:
PHPMetrics by Jean-François Lépine https://twitter.com/Halleck45
[LogicException]
No file found

And I expected this to happen:

I expect to get full report for all files in current directory and sub-directories (if they exist).

Update:
If i use this command:
"phpmetrics --report-html=myreport.html ."
Everything works as expected.

**Comment by Halleck45** [comment]
Your directory contains the ̀test` expression, that's why it is ignored.

You can try with the following command:

```
phpmetrics --report-html=myreport.html --excluded-dirs="vendor" /Users/maksimboguslavsky/repositaries/bankiru_auto_tests/
```

**Comment by shurale** [comment]
I have similar problem. On big project (633 files, 250e3 lines of code) phpmetrics somewhere write about logical exception. It correlate with size of file list. With short directory name (file list 25 kb) it work, with full path and medium directory name (file list 44 kb) it work, with full path and long directory name (file list 87 kb) it write "No file found"
PhpMetrics v1.10.0
PHP 5.6.24

**Comment by UFOMelkor** [comment]
Do your long and medium directory names match one of this: [`Tests|tests|Features|features|\.svn|\.git|vendor|node_modules|cache`](https://github.com/ufomelkor/PhpMetrics/blob/86092bdf1eb68d6906ec7a76096d364352a6827e/src/Hal/Application/Config/TreeBuilder.php#L48-L48)

**Comment by shurale** [comment]
Yes, directory tree contains directories .git, .svn, and tests

**Comment by Halleck45** [comment]
Hi,

this issue is outdated since v2 was released. So I close it. Thanks for your report !
