### ISSUE TITLE
PHP Parse error with phpmetrics.phar v1.10.0

### ISSUE THREAD

**Issue by adrien-thierry** [phpmetrics/PhpMetrics#219]
Hi,

I've installed PhpMetrics version v1.10.0 as phar archive, with PHP 5.4.24 (cli) on Windows 10

When I run this command: 

```
php phpmetrics.phar folder
```

I get this output:

```
PHPMetrics by Jean-Fran├ºois L├®pine <https://twitter.com/Halleck45>

PHP Parse error:  syntax error, unexpected 'list' (T_LIST) in phar://phpmetrics.phar/vendor/symfony/config/Definition/ArrayNode.php on line 335

Parse error: syntax error, unexpected 'list' (T_LIST) in phar://phpmetrics.phar/vendor/symfony/config/Definition/ArrayNode.php on line 335
```

**Comment by adrien-thierry** [comment]
Works well with php-5.6.18

**Comment by crazy-max** [comment]
For me on PHP 5.3.13 i've got this error :

```
Parse error: syntax error, unexpected '[' in phar://D:/neard-build/launch/tools/phpmetrics/phpmetrics1.10.0/phpmetrics.phar/vendor/hoa/core/Core.php on line 99

Call Stack:
    0.0145     551160   1. {main}() D:\neard-build\launch\tools\phpmetrics\phpmetrics1.10.0\phpmetrics.phar:0
    0.0146     544696   2. require_once('phar://D:/neard-build/launch/tools/phpmetrics/phpmetrics1.10.0/phpmetrics.phar/vendor/autoload.php') D:\neard-build\launch\tools\phpmetrics\phpmetrics1.10.0\phpmetrics.phar:15
    0.0149     562808   3. ComposerAutoloaderInitc0c67c56ac986777bdd635d269875baf::getLoader()
phar://D:/neard-build/launch/tools/phpmetrics/phpmetrics1.10.0/phpmetrics.phar/vendor/autoload.php:7
    0.0177     874872   4. composerRequirec0c67c56ac986777bdd635d269875baf() phar://D:/neard-build/launch/tools/phpmetrics/phpmetrics1.10.0/phpmetrics.phar/vendor/composer/autoload_real.php:45
```

**Comment by crazy-max** [comment]
Nevermind i just saw the travis conf ^^

**Comment by Halleck45** [comment]
The problem comes from [symfony code][https://github.com/symfony/config/blob/master/Definition/ArrayNode.php#L335), which is not compatible with PHP 5.3.

Can you try with another version of PHP ?

**Comment by UFOMelkor** [comment]
Perhaps we should build the phar with the 2.x version of symfony?

**Comment by adrien-thierry** [comment]
Works for me with php 5.5 & 5.6 (windows & linux)

**Comment by franciscocabral** [comment]
I'm using:
Yii Framework
Windows 10
PHP 5.6.13
PhpMetrics 1.10

I'm getting tons of warnings: 
[![print](http://img.prntscr.com/img?url=http://i.imgur.com/42jdlKt.png)](http://img.prntscr.com/img?url=http://i.imgur.com/42jdlKt.png)

if I try to run in all files from my project:
[![print](http://img.prntscr.com/img?url=http://i.imgur.com/KqFlodw.png)](http://img.prntscr.com/img?url=http://i.imgur.com/KqFlodw.png)

but if I run in some files, it works.

**Comment by UFOMelkor** [comment]
Timezone: It's an error triggered by PHP itself and not related to PHPMetrics. You can set the timezone within your `php.ini`:
```
date.timezone = 'Europe/Berlin'
```

For the memory limit problem see #188. You can avoid it for now by setting the memory limit within your `php.ini` or setting it as a runtime parameter:
```
php -dmemory_limit=2048M phpmetrics.phar […]
```

**Comment by leandrocr** [comment]
Guys I had to download an older version to make it work:
wget https://github.com/phpmetrics/PhpMetrics/raw/v1.9.2/build/phpmetrics.phar
