### ISSUE TITLE
Cyclomatic Complexity of switch is calculated inappropriately

### ISSUE THREAD

**Issue by halmai** [phpmetrics/PhpMetrics#222]
Hi,

I've installed PhpMetrics v1.10.0 with composer.

I have the following php code:

```
<?php
    $i = $_GET[ "i" ];
    switch($i) {
        default:
            print "unknown";
            break;

    }
    print $sum;
```

When I run this command:

```
phpmetrics  --report-csv=myreport.csv ./
```

then I get the result in the csv file that the Cyclomatic Complexity of this code is 2. 

I think it should be 1 because there is only one way to execute the code. 

Similarly, if I add one case branch to the switch statement then the CC will be 3 instead of two. That switch statement is equivalent to an if-the-else structure, hence the CC should be 2.

**Comment by Halleck45** [comment]
Hi,

PhpMetrics uses this formula:

```
ccn = number of decision points + 1
```
as [described here (method 3)](https://books.google.fr/books?id=YnGz2ghKF-gC&pg=PA229&lpg=PA229&dq=mc+cabe+decision+point+1+%2B&source=bl&ots=kpcyU3W6Fv&sig=z2CEs1hG-d8k0UL5cv2_uHPKsRY&hl=fr&sa=X&ved=0ahUKEwj5jcuAnZrTAhVBLhoKHQ5BBnoQ6AEIPDAE#v=onepage&q=mc%20cabe%20decision%20point%201%20%2B&f=false)

**Comment by halmai** [comment]
The example text of Method 3 you linked refers to the diagram 12.14 which does not exist in the file, I think it should be 12.11 but it is clear anyway. Thanks.
