### ISSUE TITLE
Explore - minify tree

### ISSUE THREAD

**Issue by fribergr** [phpmetrics/PhpMetrics#227]
Hi,

I've installed PhpMetrics 1.10.0 with composer.
I'm running it through ant with the following parameters:

```
 <target name="phpmetrics-ci" depends="prepare" description="Various maintainability checks">
   <exec executable="${basedir}/vendor/bin/phpmetrics">
     <arg value="--report-html=build/phpmetrics.html" />
     <arg value="--report-xml=build/phpmetrics.xml" />
     <arg value="--violations-xml=build/violations.xml" />
     <arg value="--chart-bubbles=build/chart.svg" />
     <arg value="--extensions=php" />
     <arg value="--offline" />
     <arg value="--excluded-dirs=vendor|provider" />
     <arg path="${basedir}/trunk/web" />
   </exec>
 </target>
```

The parent/child list in Explore-tab is a bit annoying since it does include parents that are not relevant. Am I doing something wrong or is this indeed a bug?

Below you can see what I mean by "not relevant":
![explore_minify](https://cloud.githubusercontent.com/assets/4725627/15890179/a431db20-2d6e-11e6-8afd-52a01ee4703c.png)

Best regards,
Robin

**Comment by UFOMelkor** [comment]
I would agree that the usability could be better. Something we should enhance at least for v2.

**Comment by Halleck45** [comment]
Hi,

I close this outdated issue (the table does not still exist in v2)
