### ISSUE TITLE
Option to disable progress bar

### ISSUE THREAD

**Issue by Webysther** [phpmetrics/PhpMetrics#230]
A option to disable progressBar as composer `--no-progress`:

![captura de tela de 2016-06-20 18-08-49](https://cloud.githubusercontent.com/assets/750007/16210429/44549500-3712-11e6-8693-6d30c2b0fc2d.png)

This is usefull when run in travis.

**Comment by mablae** [comment]
Same in Gitlab CI 😄 👍

**Comment by Halleck45** [comment]
Hi,

PhpMetrics has now a `--quiet` option
