### ISSUE TITLE
Infinite loop when running as a Symfony 3 console application

### ISSUE THREAD

**Issue by joostelders** [phpmetrics/PhpMetrics#234]
Hi,

I've installed PhpMetrics 1.10.0 with composer.

When I run phpmetrics as a symfony 3 console application, like: 

```
$metrics = new PhpMetricsApplication();
$metrics->setAutoExit(true);

$input = new ArrayInput(array(
'--report-json' => '/Users/joost/game/source/metrics/hoi.json',
'path' => '/Users/joost/game/source/metrics/2016-07-21_1469084167_5790720766610.php'
)
);

$output = new BufferedOutput();
$metrics->doRun($input, $output);
$content = $output->fetch();

return new Response($content);
```

Phpmetrics gets stuck in an infinite loop in the SyntaxChecker class at:

`$output = shell_exec(sprintf('"%s" -l %s 2>&1', $php, escapeshellarg($filename)));`

I get no errors when I run phpmetrics from the terminal, checking the same php file.

**Comment by Halleck45** [comment]
Ok, thanks for your report :+1: . I'll try to fix it as soon as possible

**Comment by Halleck45** [comment]
I'm sorry, I'll close this issue : it's outdated since v2 was released
