### ISSUE TITLE
PhpMetrics v2.0.0 warnings on analyze folder

### ISSUE THREAD

**Issue by clagiordano** [phpmetrics/PhpMetrics#237]
```bash
/usr/local/bin/phpmetrics --version
PhpMetrics v2.0.0 <http://phpmetrics.org>
by Jean-François Lépine <https://twitter.com/Halleck45>
```

using this command:
```bash
/usr/local/bin/phpmetrics --report-html=build/metrics ./src/
```

text output seems to be correct but it returns same repetitive warning, i think, on output html report:

```
PHP Warning:  array_push() expects parameter 1 to be array, float given in phar:///usr/local/bin/phpmetrics/src/Hal/Metric/Consolidated.php on line 95
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpmetrics:0
PHP   2. Hal\Application\Application->run() /usr/local/bin/phpmetrics:16
PHP   3. Hal\Report\Html\Reporter->generate() phar:///usr/local/bin/phpmetrics/src/Hal/Application/Application.php:67
PHP   4. Hal\Metric\Consolidated->__construct() phar:///usr/local/bin/phpmetrics/src/Hal/Report/Html/Reporter.php:44
PHP   5. array_push() phar:///usr/local/bin/phpmetrics/src/Hal/Metric/Consolidated.php:95
```

and 

```
PHP Warning:  array_push() expects parameter 1 to be array, float given in phar:///usr/local/bin/phpmetrics/src/Hal/Metric/Consolidated.php on line 95
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpmetrics:0
PHP   2. Hal\Application\Application->run() /usr/local/bin/phpmetrics:16
PHP   3. Hal\Report\Html\Reporter->generate() phar:///usr/local/bin/phpmetrics/src/Hal/Application/Application.php:67
PHP   4. Hal\Metric\Consolidated->__construct() phar:///usr/local/bin/phpmetrics/src/Hal/Report/Html/Reporter.php:44
PHP   5. array_push() phar:///usr/local/bin/phpmetrics/src/Hal/Metric/Consolidated.php:95
PHP Warning:  array_sum() expects parameter 1 to be array, float given in phar:///usr/local/bin/phpmetrics/src/Hal/Metric/Consolidated.php on line 103
```

thanks for your work!

**Comment by Halleck45** [comment]
Hi,

I cannot reproduce :(.

Can you debug manually please, as following ?

1. `git clone https://github.com/phpmetrics/PhpMetrics.git && cd PhpMetrics`
2. edit the file `src/Hal/Metric/Consolidated.php` line 94

```php
// file src/Hal/Metric/Consolidated.php line 94
foreach ($avg as $k => &$a) {
    if(!is_array($avg->$k)) {
         var_dump($k);
         var_dump($avg->$k);
    }
    array_push($avg->$k, $item->get($k));
}
```

3. run `php ./bin/phpmetrics --report-html=build/metrics ./src/`
4. and finally copy-paste the output in this issue ?

Or can you provide the files you're analyzing ?

Thank's a lot !

**Comment by clagiordano** [comment]
I cloned the repo on the branch master but I see this:

```bash
PhpMetrics [master|✔] 
$ php ./bin/phpmetrics --version
PhpMetrics, by Jean-François Lépine (https://twitter.com/Halleck45) version v1.10.0
```

is the correct branch for the v2 source code?

**Comment by clagiordano** [comment]
I see the commit log history ad the right branch seems to be version2_ast

**Comment by clagiordano** [comment]
A little suggestion, after cloning branch or pull new commits I usually exec command 

```bash
composer install
```

but in this case I need to execute

```bash
composer update
```

because the composer.lock file is ignore by into .gitignore file, then my suggestion is:

I recently discovered that it is a better solution to keep composer.lock files under version control for better consistency of installed libraries and to be sure that on all environment there are exactly the same versions of the libraries installed, this obviously implies the need to commiting changes after each composer update because composer.lock will be updated.

Thanks!

**Comment by clagiordano** [comment]
See #236 for more informations.

I replaced on Consolidated class:

```php
foreach ($avg as $k => &$a) {
    array_push($avg->$k, $item->get($k));
}
```

with your provided code:

```php
foreach ($avg as $k => &$a) {
    if (!is_array($avg->$k)) {
        var_dump($k);
        var_dump($avg->$k);
    }
    array_push($avg->$k, $item->get($k));
}
```

and the var_dump outputs this:

```bash
PhpMetrics/src/Hal/Metric/Consolidated.php:96:
string(3) "ccn"
PhpMetrics/src/Hal/Metric/Consolidated.php:97:
double(7)
```

**Comment by Halleck45** [comment]
Oups, sorry for the incorrect instructions :/

Thanks for your help. I'll fix it soon

**Comment by clagiordano** [comment]
No problem, just a tips

**Comment by Halleck45** [comment]
@clagiordano Ok I've reproduced this warning with your code and under PHP7.0.

I don't know why, but [this commit](https://github.com/phpmetrics/PhpMetrics/commit/cdec4c61aebf26e2cabf47eebbd9e7816f7fc034) fixed it.

Can you confirm that this issue is fixed ?

**Comment by clagiordano** [comment]
Perfect, now works fine!

Thanks!

**Comment by clagiordano** [comment]
@Halleck45  About referenced var into foreach loop see this link:

[http://stackoverflow.com/questions/13650898/php-pass-by-reference-error-after-using-same-var](http://stackoverflow.com/questions/13650898/php-pass-by-reference-error-after-using-same-var)
