### ISSUE TITLE
autoload in 2.00rc refers to wrong directory

### ISSUE THREAD

**Issue by mangalores** [phpmetrics/PhpMetrics#239]
Hi,

Thank you for taking the time to report this bug :+1:

Run `phpmetrics --version` to get the version of PhpMetrics. 

**The latest version of PhpMetrics is v1.10.0.**. Please try to update PhpMetrics and check if the bug persist before submitting new issue.
 
Here is a template for your issue. Please replace the words between braces with the right informations. 

---- 

Hi,

I've installed PhpMetrics v2.0.0 with composer 

When I run this command from console: vendor/bin/phpmetric --report-html=test.html

The command fails on require_once when including the autoload.php as it refers to "../autoload.php" from "vendor/phpmetrics/phpmetrics/bin"

It should have the proper autoload reference.

Was testing the rc due to its change of JS files for html as our Jenkins has https breaking .

Regards,

Holger

**Comment by Halleck45** [comment]
Hi,

thanks for your help :)

This should be fixed by [this commit](https://github.com/phpmetrics/PhpMetrics/commit/0a13e60b67fc5d3e888e5eb82e8afde0128ff55e). 
Can you confirm this issue is fixed please ?

```
mkdir /tmp/phpmetrics-fix && cd /tmp/phpmetrics-fix
composer require "phpmetrics/phpmetrics:dev-version2_ast"
./vendor/bin/phpmetrics --version
```

**Comment by Halleck45** [comment]
ping @mangalores :)

**Comment by Halleck45** [comment]
I hope this issue is now fixed by [this commit](https://github.com/phpmetrics/PhpMetrics/commit/0a13e60b67fc5d3e888e5eb82e8afde0128ff55e). Feel free to reopen it.

Thanks for your report !
