### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by iMega** [phpmetrics/PhpMetrics#244]
Hi!

I very like the app PhpMetrics. I tried to make for app the docker image. 
And my result https://hub.docker.com/r/imega/phpmetrics very lightweight 13 MB. 
Maybe it will interest you?

Best regards.

**Comment by Halleck45** [comment]
Cool ! :clap:

what do you think about versioning your `Dockerfile` in the PhpMetrics repository ? It will allow to update image on each build. This Dockerfile should be stored in the `artifacts/docker` directory.

We can envisage a postbuild hook that build and publish the docker image to hub.docker.com (that's the current process for the `phar` and the `deb` artifact).

**Comment by iMega** [comment]
I'm all in favor of it! 👻 I will try to briefly describe how I created the image. https://github.com/imega-docker/phpmetrics. To create a small size (docker image), I use a builder. The builder makes `rootfs.tar.gz` and the file is added to `scratch`.

```
$ make build
$ docker build -t phpmetrics .
$ cd to/php/project
$ docker run --rm -v `pwd`:/data phpmetrics --report-html=report .
```

To use hub.docker.com need rootfs.tar.gz stored in the repository. (e.g. artifacts/docker). Next as usual to work with webhook.

If the 'idea' of the `rootfs.tar.gz` you do not like, I ready to listen to your proposal.

**Comment by iMega** [comment]
PS: You have a resource that can automate the creation of `rootfs.tar.gz`?

**Comment by herloct** [comment]
Me too, trying to build my own docker image for PhpMetrics here: https://github.com/herloct/docker-phpmetrics

Just using plain php base image and `phpmetrics.phar`, the size is 27MB.  
I think it easier like this than using builder.

**Comment by Halleck45** [comment]
yes, I prefer the @herloct implementation (easier to maintain and to understand according to me).

@herloct , can you open a PR with your Dockerfile in a `artifacts/docker` directory ? Or can I reuse your `Dockerfile` directly (under MIT licence) ?

Thanks !

**Comment by herloct** [comment]
> Or can I reuse your Dockerfile directly (under MIT licence) ?

Please, feel free to :D  

But i think it might be better to test the build image before pushing it to the Docker Hub, maybe we could add some script to build-test-publish the docker image on current `.travis.yml`.

Sorry for the very late response
