### ISSUE TITLE
Serve JS/CSS resources through HTTPS

### ISSUE THREAD

**Issue by dereckson** [phpmetrics/PhpMetrics#249]
Hi,

I've installed PhpMetrics v1.10.0 with composer.

When I run this command:

```
phpmetrics --report-html=build/phpmetrics-report.html app/
```

I get this output:

- the application generates successfully the report
- the report contains unsafe resources (http:// link to CSS for example)

And I expected this to happen:

- the application generates successfully the report
- the report can be read on a HTTPS server

More precisely:

- there is a link to http://nvd3.org/assets/css/nv.d3.css
- https://nvd3.org/assets/css/nv.d3.css doesn't have a valid certificate (server has a certificate for *.github.com)
- same for http://nvd3.org/assets/js/nv.d3.js 
- http://d3js.org/d3.v3.min.js could directly be replaced by https://d3js.org/d3.v3.min.js

**Comment by samizdam** [comment]
Do you see #223  ? This fix solve you issue, in theory. 
But, this commit merged in master after version 1.10.0 was released.

**Comment by dereckson** [comment]
Perhaps a new release in the 1.x would then be welcome.

**Comment by azzeddinefaik** [comment]
Hi When this will be released, v2.0.0 still RC. could not install it using composer ?

**Comment by Halleck45** [comment]
I close this issue in favor of #251
