### ISSUE TITLE
http://www.phpmetrics.org/images/phpmetrics-maintenability.png served from HTTP

### ISSUE THREAD

**Issue by dereckson** [phpmetrics/PhpMetrics#251]
Hi,

I've installed PhpMetrics v2.0.0 with composer.

When I run this command:

```
phpmetrics ...
```

I get this output:

```
relations.html:72 Mixed Content: The page at 'https://.../build/phpmetrics/relations.html' was loaded over HTTPS, but requested an insecure image 'http://www.phpmetrics.org/images/phpmetrics-maintenability.png'. This content should also be served over HTTPS.
```

And I expected this to happen:

An image served through HTTPS, which is not currently possible, as the image is hosted on an HTTP only server.

**Comment by Halleck45** [comment]
phpmetrics.org is hosted on Github pages, without HTTPS support :/

I hesitate to move website on my own server (with HTTPS). Do you know any sponsor to help me with hosting ?

**Comment by dereckson** [comment]
Currently, HTTPS on GitHub Pages work only with a GitHub domain; not with another domain used as CNAME, 

The Nasqueron project can host it (see https://launch.nasqueron.org/ for a presentation) if you wish, either with a CD approach (commit to the Git repository, a Jenkins job trigger is fired deployment) or a more traditional approach (a SFTP/SSH account for manual deployment).

**Comment by dennisdegreef** [comment]
Can't this content just be embedded in the result?

**Comment by UFOMelkor** [comment]
@dereckson Did #302 solve the issue for you?

**Comment by dereckson** [comment]
for me?
