### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by dereckson** [phpmetrics/PhpMetrics#252]
The relations chart uses https://gist.github.com/mbostock/7607999 (credited in the source code through the external visualisation service http://bl.ocks.org/mbostock/7607999).

This chart is GPLv3, a copyleft license.

If the source code used by PhpMetrics reuses this source code, it means _something_ is GPLv3. 

I guess two interpretations are possible:
* PhpMetrics is a code generator licensed in MIT and produce a GPLv3 licensed report
* PhpMetrics incorporates GPLv3 code and so is licensed under GPLv3

This legal detail should be sorted of.

**Comment by Halleck45** [comment]
Hi,

thanks you ! It's a good question. I think that PhpMetrics v1 should follows the GPMv3 licence. I'll fix it as soon as possible.

PhpMetrics v2 does not use this component, and will be released under MIT licence.
