### ISSUE TITLE
McCabe's Cyclomatic Complexity bad calculation with "?" occurrences.

### ISSUE THREAD

**Issue by niconoe-** [phpmetrics/PhpMetrics#253]
Hi,

I've installed PhpMetrics 1.10.0 with composer.

I found that running the metrics on files that use the nullable types on functions/methods return have McCabe's cyclomatic complexity uping while it should not.
The reason of this is the token parsing that add 2 points of CC for each "T_STRING" that are "?".

I found a workaround by checking the previous tokens (T_WHITESPACE and T_STRING that is a ":" or directly a T_STRING that is a ":"), but I don't think it is a good way to do this.

Probably the best way to calculate the CC is now to use the 1st McCabe's method.

Thanks.
Regards,

**Comment by niconoe-** [comment]
Just for information, my workaround is adding those lines in the file src/Hal/Metrics/Complexity/Component/McCabe/McCabe.php between line 62 and 63:

```
if ($tokens[$key-1]->getType() === T_WHITESPACE && $tokens[$key-2]->getValue() === ':') {
     break;
}
if ($tokens[$key-1]->getValue() === ':') {
    break;
}
```

It requires also to define the `$key` variable in the `foreach` loop, at line 41.

I know this is awful, and must probably be defined better, but it's temporary.

**Comment by Halleck45** [comment]
PhpMetrics nows uses [PhpParser](https://github.com/nikic/PHP-Parser). I close this issue. Thanks for your help !
