### ISSUE TITLE
adjust PhpMetrics

### ISSUE THREAD

**Issue by StephanKrauss** [phpmetrics/PhpMetrics#255]
Hi, I am a beginner in the field of php metrics.

I would like to change 2 things in PhpMetric.

Where can I find the configuration of PhpMetric?
I want to create a custom configuration file.

How can I integrate my own sample files into the menu?

Best regards

Stephan Krauss

**Comment by Halleck45** [comment]
Hi,

PhMetrics v2 does not support configuration file yet. I'll add it as soon as possible.

Concerning links in the menu, I'm not sure that's a good idea : it will complicate the code.

I close this issue. Do not hesitate to reopen it if needed
