### ISSUE TITLE
PhpMetrics 2.0 should use nikic/php-parser at least in version 3

### ISSUE THREAD

**Issue by niconoe-** [phpmetrics/PhpMetrics#258]
Hi,

I'm running PhpMetrics in version 1.10 and I'm trying to make it work with the new version 2.0.0.

I encounter a trouble with the parser that is unable to parse code from PHP 7.1.

Please, can you use the nikic/php-parser package in version 3.0.0 or above to make PHP 7.1 code parsable in the version 2.0.0 of PhpMetrics?

Thanks a lot.

Regards,

**Comment by Halleck45** [comment]
Hi,

you're right. The [`composer.json`](https://github.com/phpmetrics/PhpMetrics/blob/master/composer.json#L37) now requires `v3.*̀

Thanks for your help !
