### ISSUE TITLE
Travis fails because of PHPUnit v6.0.0

### ISSUE THREAD

**Issue by niconoe-** [phpmetrics/PhpMetrics#261]
Hi again,

In PhpMetrics v2, you `require-dev` PHPUnit at least in version 4.8.27 (>= 4.8.27).

But since few days ago, PHPUnit 6.0.0 has come and lots of changes are in there, especially **they namespaced all their classes!**
Because of this, in PHP 7, you are trying to run PHPUnit with removed classes, so it fails.

To fix this, you have 2 solutions:
1) Change your composer.json to not get over PHPUnit 6 (so stop to 5.7.13)
2) Change your tests sources to use namespaced classes.

I will recommand to you the 1st solution as you may need to make your tool works with PHP 5.5 and PHPUnit 6.x has a PHP 7 requirement.

I think you should do this ASAP otherwise all builds will fails to PHP 7.

Have a nice day.
Regards,

**Comment by Halleck45** [comment]
Hi,

thank you for your help. I've just changed the `composer.json` to :
```json
    "require-dev": {
        "phpunit/phpunit": ">=4.8.27,<=5.7.13"
    },
```

In the future I will try to update unit tests...

I close this issue.
