### ISSUE TITLE
Drop support for ancient and unsupported PHP versions

### ISSUE THREAD

**Issue by Fleshgrinder** [phpmetrics/PhpMetrics#268]
Supporting 5.6 is fine as long as it receives security fixes, however, anything else is just a crime, sorry.

https://php.net/supported-versions

**Comment by Halleck45** [comment]
Hi,

yes, I'm agree but... :)

Static analyzer are often used with legacy (old) code, on old PHP versions and old platforms. Today, supporting PHP 5.4 and 5.5 is easy, so I'll try to support them for few months. 

What do you thin about it ?

**Comment by Fleshgrinder** [comment]
Supporting the analyzation of old versions is imho OK, but the program itself should require newer versions. It will allow you to implement new features more easily, and it will help the PHP ecosystem as a whole to migrate faster to the latest versions.

One of the biggest problems for PHP to become better is the slow adoption of new versions. You can support PHP by not supporting old versions.

**Comment by Halleck45** [comment]
Hi,

I've removed to support of `PHP 5.4`. Now I'll support only PHP versions supported by the [PHPParser@(https://github.com/nikic/PHP-Parser/blob/master/composer.json)

Thanks for this discussion :) . Can I close this issue ?

**Comment by melbit-dannyw** [comment]
I don't think it's necessarily a good idea to remove support for php 5.3 or 5.4 as these versions are the current versions supported by Red Hat for RHEL6 and RHEL7 in production servers.  Red Hat backports any security fixes to these versions to provide long term support to enterprise customers who have lots of money invested in their applications.

To clarify though, I see no problem with phpmetrics itself requiring php > 5.4 to run, as long as it can still analyse older code.  Having said that, it's up to you, as you are the maintainer with limited time and resources, and perhaps tools like this are a privilege of using an up-to-date php version.

Or, you could just let people know what older release versions they need to use for older php versions.

I worked through these arguments as I typed out this response.  :-)

**Comment by UFOMelkor** [comment]
You can rest assured, this whole issue is just about dropping support for older versions to run phpmetrics. The PHP version of the analyzed code is just restricted by the supported versions of [PHP-Parser](https://github.com/nikic/PHP-Parser):
> This is a PHP 5.2 to PHP 7.1 parser written in PHP. Its purpose is to simplify static code analysis and manipulation.
