### ISSUE TITLE
phpmetrics --version does not report the right version number.

### ISSUE THREAD

**Issue by mageekguy** [phpmetrics/PhpMetrics#274]
I have installed the version 2.1 of PhpMetrics via `php composer.phar global require 'phpmetrics/phpmetrics'`.
The contents of my `$HOME/.composer/composer.json` is:

```
{
    "require": {
        "phpmetrics/phpmetrics": "^2.1"
    }
}
```

However, output of `phpmetrics --version` is:

```
PhpMetrics v2.0.0 <http://phpmetrics.org>
by Jean-François Lépine <https://twitter.com/Halleck45>
```

**Comment by Halleck45** [comment]
Hi,

thanks for your help @mageekguy . Glad to see you here :)

This issue is fixed with #275
