### ISSUE TITLE
[feature request] show composer installed dependencies

### ISSUE THREAD

**Issue by garak** [phpmetrics/PhpMetrics#284]
Currently, the box about dependencies is showing the required version and the latest version of each package.
It would be nice to get another column with the actually installed version.

**Example** for `ramsey/uuid-doctrine`, currently shown:

|Package|Required|Latest|License|
|---|---|---|---|
|ramsey/uuid-doctrine|^1.2|1.3.0|MIT

With proposed improvement:

|Package|Required|Installed|Latest|License|
|---|---|---|---|---|
|ramsey/uuid-doctrine|^1.2|1.2.9|1.3.0|MIT

As a bonus, a confrontation between installed and latest could be colored in green in case of match and in red otherwise, highlighting packages that are not up to date

**Comment by vpassapera** [comment]
I can't even get that to show up...
