### ISSUE TITLE
Invalid hyperlink to phpmetrics.org

### ISSUE THREAD

**Issue by SenseException** [phpmetrics/PhpMetrics#289]
On phpmetrics 2.2.0, links to the PHPMetrics homepage, in console and in the generated report, are http://phpmetrics.org.

Currently http://phpmetrics.org fails, but http://www.phpmetrics.org works fine. I suggest to enable http://phpmetrics.org too instead of making a PR to fix all the domain names in the project.

**Comment by niconoe-** [comment]
Moved on the related phpmetrics/website project.
