### ISSUE TITLE
Incorrect Coupling counts

### ISSUE THREAD

**Issue by auroraeosrose** [phpmetrics/PhpMetrics#291]
Phpmetrics version 2.2.0 installed via composer

Calculations for efferent coupling in phpmetrics are counting identical (duplicate) classes as additional couplings
this is incorrect

Pdepends shows effluent coupling of 4 for the controllers\base class shown below

When dumping the calculated graph using $graph->asString() inside  Hal\Metric\System\Coupling I am getting this as a result

```

Controllers\Base -> Psr\Container\ContainerInterface;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> ValidationException;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> ValidationException;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> Psr\Http\Message\ResponseInterface;
Controllers\Base -> InvalidArgumentException;
Controllers\Base -> InvalidArgumentException;
Controllers\Base -> InvalidArgumentException;

```

The phpmetrics output gives this as effluent coupling of 20 - which is utterly incorrect
The value should be 4

I'm not exactly sure what is failing that is allowing these duplicate nodes to be added - still digging through code

**Comment by auroraeosrose** [comment]
Looks like the graph class is adding duplicate edges

There is no check to see if an identical Edge (one with the exact same to and from node) already exists in the graph

The correct fix would be to add a $this->hasEdge($to, $from) method and check it before adding an edge, or a check inside the addEdge() method in the Graph class to keep from getting duplicates

For now this is working as a horrid workaround - add at src/Hal/Metric/System/Coupling/Coupling.php#L44

```
$skip = false;
foreach($graph->getEdges() as $edge) {
    if($edge->getTo() == $to && $edge->getFrom() == $from) {
        $skip = true;
	break;
    }					
}

if($skip == false) {
    $graph->addEdge($from, $to);
}
```

This creates the correct coupling information and the statistics then match (or are very close) to those output by pdepends

**Comment by ing200086** [comment]
I am curious does this fix also work if constants are used. As it is right now the following code provides coupling of 3:

```php
class Foo
{
    public function zero()
    {
        return 0;
    }

    public function nothing()
    {
        return 0;
    }

    public function nada()
    {
        return 0;
    }
}
```

But I believe it should return 1. Even if I change to have them all return a constant (i.e. self::ZERO) the LCOM number is still 3. It should be obvious, but I will say it anyway.... this is only example code to show the issue.

**Comment by FractalizeR** [comment]
I've posted a PR to fix this. Please, feel free to review it.

**Comment by Halleck45** [comment]
@niconoe- I think that this issue should be reopened given that the PR is not yet merged

**Comment by niconoe-** [comment]
The PR was the #304 and was merged yesterday at noon. Or maybe there is another PR related to this issue?

**Comment by Halleck45** [comment]
Oh yes you're right. I close this issueagain :)
