### ISSUE TITLE
What happened with --report-json option?

### ISSUE THREAD

**Issue by fracz** [phpmetrics/PhpMetrics#294]
The 2.x version of metrics does not have a super-useful option for furhter processing, that is, generating a JSON report with `--report-json` flag.

The HTML output is fancy, undoubtedly, but is hardly processable by another tools (like CI server, some stats calculator etc).

Why was it removed? Do I need some plugin for this?

**Comment by bursonic** [comment]
Same question. Had to stick to 1.* only because of this option.

**Comment by niconoe-** [comment]
I don't remember which information you had in this reporting file in 1.* but can you compare with the generated `js/classes.js` when using the `--report-html` option in the 2.*?
If it fits with your expectations and it contains all data you need, maybe we can just re-integrate this option giving you only this file?

In this case, I need to ask to @Halleck45 before if this sort-of rollback is in his plans.

**Comment by Halleck45** [comment]
Hi,

json is not the same of the v1, but what do you think about https://github.com/phpmetrics/PhpMetrics/pull/301 ?
