### ISSUE TITLE
Keep track of past data

### ISSUE THREAD

**Issue by ouhman** [phpmetrics/PhpMetrics#295]
On the [demo website](http://www.phpmetrics.org/report/latest/index.html) and as shown in the screenshot attached it seems like it is possible to keep track of past data when re-running phpmetrics.

I couldn't find anywhere in the doc how do do that. Is this feature available out of the box? If no how can I set this up?

![php-metrics-data](https://user-images.githubusercontent.com/39566/29064740-40e33fe4-7c2a-11e7-9b79-58684c1e176f.png)

**Comment by niconoe-** [comment]
Simply run the phpmetrics command using the exact same output options you defined and the tool will manage this persistance automatically.

Running `phpmetrics --report-html=myProject/reports/phpmetrics` the first time will create the file `js/history-1.json`. Run it again and it will create the file `js/history-2.json`, etcetera...

**Comment by ouhman** [comment]
Thanks! Would be good to have that written in the doc :)

**Comment by Halleck45** [comment]
@ouhman Yes you're right. Do not hesitate [to contribute](https://github.com/phpmetrics/website) :)
