### ISSUE TITLE
Include a folder

### ISSUE THREAD

**Issue by johnrobertporter** [phpmetrics/PhpMetrics#298]
Hi,

I've installed PhpMetrics v2.2.0 with composer

I am wondering if there is any way to include a folder? I have an API that uses composer to load the separate packages I use (into a different folder than vendor) to build out the API functionality. I could really use a report of the whole lot together, but have no idea how to get phpmetrics to see this components folder.

**Comment by niconoe-** [comment]
When running your `phpmetrics` command, you set the list of files/folders you want to parse, separated by a comma.

`$> phpmetrics project1/src,project2/src,...`

Is this what you're looking for?

**Comment by johnrobertporter** [comment]
Ahhh, ok, I get it now. Thanks!

**Comment by johnrobertporter** [comment]
Could you add that to the docs, as it's an unknown otherwise :)

**Comment by niconoe-** [comment]
`phpmetrics --help` gives you this. :smile:.
