### ISSUE TITLE
 Problem in running the html report in PhpMetrix

### ISSUE THREAD

**Issue by BhavyaL** [phpmetrics/PhpMetrics#300]
Hi,

Thank you for taking the time to report this bug :+1:

Run `phpmetrics --version` to get the version of PhpMetrics. 

**The latest version of PhpMetrics is v2.0.0-rcalphaalphaalphaalphaalphaalpha.**. Please try to update PhpMetrics and check if the bug persist before submitting new issue.
 
Here is a template for your issue. Please replace the words between braces with the right informations. 

---- 

Hi,

I've installed PhpMetrics {version} {with composer | as phar archive}.

When I run this command:
php ./vendor/bin/phpmetrics --report-html=myreport.html.
```
phpmetrics ...
```

I get this output:

```if command -v 'cygpath' >/dev/null 2>&1; then
        # Cygwin paths start with /cygdrive/ which will break windows PHP,
        # so we need to translate the dir path to windows format. However
        # we could be using cygwin PHP which does not require this, so we
        # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
        if [[ $(which php) == /cygdrive/* ]]; then
                dir=$(cygpath -m "$dir");
        fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/phpmetrics" "$@"


```

And I expected this to happen:

```Problem in Running the Command for Phpmetrix

```

**Comment by niconoe-** [comment]
This issue has no description.
Closing.

**Comment by Halleck45** [comment]
@BhavyaL Hi, that's look more a Cygwin issue, or incorrect configuration of cygwin, than a PhpMetrics issue.

Do not hesitate to reopen this issue if you think that's a PhpMetrics bug.
