### ISSUE TITLE
run phpmetrics in directory with spaces in the path

### ISSUE THREAD

**Issue by pavarnos** [phpmetrics/PhpMetrics#315]
I've installed PhpMetrics 2.3.0 with composer

When I run this command:

```
./vendor/bin/phpmetrics --report-html=./var/phpmetrics --git ./src
```

I get this output:

```
.......Executing system analyzes...sh: line 0: cd: /Users/stevep/Documents/overseas/isv/Personnel: No such file or directory
```

And I expected this to happen:

```
................
```

The shellexec in Hal\Metric\System\Changes\Git\GitChanges does not appear to cope with spaces in the path. The full path to my project is `/Users/stevep/Documents/overseas/isv/Personnel Database/l2s` (note the space). Maybe use symfony/process ?

This _may_ also be a problem for the Composer metrics as well: the html report says "no composer.json file found" even though composer.json exists in the directory phpmetrics was run from

**Comment by niconoe-** [comment]
Thank si for your feedback.
I'll make some tests but I think if we ensure paths are quoted when having spaces, it should be ok.

In general matters, you should avoid paths with spaces even if it is accepted by most file-systems: phpmetrics might be not the only tool dealing spaces in paths wrong...
