### ISSUE TITLE
[Request] Add support for custom composer.lock location

### ISSUE THREAD

**Issue by skyzyx** [phpmetrics/PhpMetrics#320]
I've installed PhpMetrics v2.3.2 with Composer. When I run this command:

```bash
www/bin/phpmetrics --version
```

I get this output:

```
PhpMetrics v2.3.2 <http://phpmetrics.org>
by Jean-François Lépine <https://twitter.com/Halleck45>
```

When running PhpMetrics, my `composer.*` files are not in the same directory that I'm generating my metrics from. Here are some sample relative file paths.

```
Makefile
www/bin/phpmetrics
www/src/
www/composer.json
www/composer.lock
```

I point `www/bin/phpmetrics` at `www/src/` to generate metrics, but `composer.*` is not inside of `www/src/`.

Can you add an option to specify where my `composer.lock` file is?

<img width="539" alt="screen shot 2017-10-19 at 3 15 44 pm" src="https://user-images.githubusercontent.com/39447/31789814-637c3aac-b4e1-11e7-8b5e-98774990eb62.png">

**Comment by niconoe-** [comment]
Hi, thank you for your feedback :).

The `phpmetrics` command can take several folders/files comma-separated.

If you run phpmetrics from your project root, you should be able to have complete metrics (with the `composer.*` files) by running:
`$> phpmetrics www/bin/phpmetrics,www/src,www/composer.json,www/composer.lock`

Can you give it a try and tell me if your metrics are still not complete after your tests?
Thanks a lot.

**Comment by niconoe-** [comment]
Sorry, I meant this command:

ˋ$> www/bin/phpmetrics www/src,www/composer.json,www/composer.lock`

Regards,
