### ISSUE TITLE
Maintainability Index Range

### ISSUE THREAD

**Issue by slk500** [phpmetrics/PhpMetrics#326]
I just started using PhpMetrics. I run it on https://github.com/adamculp/refactoring101 and it says that some classes have Maintainability Index 171 but I have read here http://www.phpmetrics.org/documentation/how-to-understand-metrics.html that "Maintainability index evaluates ... the maintainability of any project. It provides a score between 0 to 118. " 
So my question is what is the range of Maintainability Index? 
Btw. in generated report when you click on PhpMetrics logo or link "PhpMetrics Static analyzer for PHP" the link address is http://phpmetrics.org/ but this address dosen't work should be http:/www./phpmetrics.org/

**Comment by niconoe-** [comment]
Hi, thank you for using PhpMetrics!

The documentation you are talking about is refering to some elements that came from the PhpMetrics V1 and it might be another calculation system.
Anyway, in the last version of PhpMetrics, the calculation's formula is the one created in 1992 by Paul Oman and Jack Hagemeister, promoted by the Software Engine Institute (SEI) in 1997:

    MI = 171 - 5.2 * log2(V) - 0.23 * CC - 16.2 * log2 (LOC) + 50 * sin (sqrt(2.4 * CM))

With:
- V = the Halstead Volume
- CC = the cyclomatic Complexity
- LOC = Lines of code
- CM = percentage of comment lines (value between 0 and 1, 1 => 100%)

This makes the MI cap to a theorical value of 221, but with those real values:
- V = 1
- CC = 0
- LOC = 1
- CM = 1.02808379178 (well, about 102,8% of comment in your code...).

In a test, I managed to reach 220,99 with a single class line declaration and about 21k lines of comments.
So, the range of the MI is [0; 221[

About your link question, some improvements are in progress here but in the server part to make http://phpmetrics.org reachable and replace the "www" subdomain.

**Comment by slk500** [comment]
Thank you for a very comprehensive answer. That's info should be on website. If you put it on github I will be happy to contribute.

**Comment by niconoe-** [comment]
Website is on github :).
You can have a look on https://github.com/phpmetrics/website.

I'm only working on the PhpMetric tool, not the website. If you want to help with this kind of documentation, it would be great!

If that's ok to you, can you close that issue please?

Thanks a lot.

**Comment by slk500** [comment]
Oh, didn't notice that. Thx.

**Comment by toniorganizer** [comment]
How to get Halstead Volume value on phpmetrics latest display version? I have difficulty determining MI, because in the formula for determining MI there must be a Halstead Volume value
