### ISSUE TITLE
phpmetrics: command not found

### ISSUE THREAD

**Issue by Akshat122** [phpmetrics/PhpMetrics#327]
Hi,

I've installed PhpMetrics .

When I run this command:

```
phpmetrics 
```

I get this output:

```
phpmetrics: command not found
```

And I expected this to happen:

```
....(something)....
```
I found a workaround for the problem (Worked for me atleast  )

export PATH=~/.composer/vendor/bin:$PATH

**Comment by niconoe-** [comment]
Hi.

Can you tell me how do you installed phpmetrics?

Was it with composer (global or not)? Using the phar?

Thanks a lot.

**Comment by Akshat122** [comment]
I tried it with a global composer

**Comment by juliendufresne** [comment]
The workaround Is the way to go. You may want to use full path if you can't edit your `.bashrc` (or `.zshrc` or ...)

**Comment by hhamon** [comment]
You must add `~/.composer/vendor/bin` directory to your `$PATH` variable to solve the issue.

**Comment by carloshc** [comment]
On command line (Linux), type:

`export PATH=$PATH:~/.composer/vendor/bin`

Also edit your **.profile** file:

`nano ~/.profile`

**Comment by Halleck45** [comment]
Hi,

I think this issue is solved. Do not hesitate to check the [documentation of composer on global packages](https://getcomposer.org/doc/03-cli.md#global).

Thanks every body for your help !!
