### ISSUE TITLE
Cache results to increase performance of consecutive runs

### ISSUE THREAD

**Issue by hakamairi** [phpmetrics/PhpMetrics#330]
Hi,
Do you plan or would you consider caching the results of the phpmetrics analysis?
Similar functionality is already implemented in phpcs --cache.

Kind regards

**Comment by Halleck45** [comment]
Hi,

hum, not sure that's a good idea. Dealing with cache is hard, debugging with cache is very hard... 

But if you want to work on a cache feature, do not hesitate to open a PR :)
