### ISSUE TITLE
Maintainability Index Formula

### ISSUE THREAD

**Issue by ing200086** [phpmetrics/PhpMetrics#332]
Something doesn't seem right with the maintainability index...

Looking at the source code it seems there is a limited range between 0 and 99.865 for the MI (assuming you have a volume, cyc complexity and lines of code equal to 1. This differs from the documented limit of 118.
```
$maintainabilityIndex = 171 - 5.2 * log($halsteadVolume) - 0.23 * $cyclomaticComplexity - 16.2 * log($eloc);
$maintainabilityIndex = min(100, max(0, $maintainabilityIndex * 100 / 171));
```

It seems like the boundaries for the maintainability are based on the original 0-170.77 range.

For example if I somehow keep the volume and cyc complexity to 1, then to reach "good code" I would be limited to under 5 lines of code (this would include the class header, namespaces, and a declare(strict_type=1) i include at the top of my code. To not have code which "has debt" then I would be limited to 55 lines of code with the same parameters.

I really hope I just don't understand how these metrics should be calculated. :/

**Comment by niconoe-** [comment]
Hi @ing200086 
The range of [0; 118] is still in the documentation but it is wrong. Please look at [this issue](https://github.com/phpmetrics/PhpMetrics/issues/326#issuecomment-342123085) to better understand how it is calculated.

Have a nice day.
Regards,
