### ISSUE TITLE
Public methods count

### ISSUE THREAD

**Issue by jakagacic** [phpmetrics/PhpMetrics#335]
Hi, I have noticed that the public methods count does not recognize getters and setters when using php7 type declarations for parameters and return types. This makes it very easy to get the following error on a good structured class, with a few private properties:

Blob / God object error
A blob object (or "god class") does not follow the Single responsability principle.

* object has lot of public methods (8, excluding getters and setters)

Is there any chance for this to be fixed?

**Comment by UFOMelkor** [comment]
Hi @jakagacic,

may I ask you for an example?
I added the following examples to the [RoleOfMethodDetectorTest](https://github.com/phpmetrics/PhpMetrics/blob/08eb64b9aeba0f752fdc1844ce1dbe19d79c3fed/tests/Metric/Helper/RoleOfMethodDetectorTest.php) and both are recognized correctly:

```php
$examples[] = ['getter', '<?php class A { function getName(): string { return $this->name; } }'];
$examples[] = ['setter', '<?php class A { function setName(string $name): void { $this->name = $name; } }'];
```

**Comment by jakagacic** [comment]
Hi @UFOMelkor, 

thank you for your answer.

I have testes both of your examples and they work as expected, but the problem seems to be when using types other then the primary ones. For example, this getter is recognized:

```php
    /**
     * @param string $role
     */
    public function setRole(string $role)
    {
        $this->role = $role;
    }
```

while this one isn't:

```php
    /**
     * @param Role $role
     */
    public function setRole(Role $role)
    {
        $this->role = $role->name;
    }
```

**Comment by UFOMelkor** [comment]
Thank your for your example, I could reproduce the error with them. I will try to find a fix for it tomorrow.
