### ISSUE TITLE
Documentation doesn't match current version

### ISSUE THREAD

**Issue by johnrobertporter** [phpmetrics/PhpMetrics#346]
The documentation displays a lot of really useful graphs, and a tabular breakdown of classes.

I feel this view would be suited for what I want to see from the reports.

Is there a way to get this view back?

**Comment by Halleck45** [comment]
Hi,

yes the documentation is not updated, and there is a mix from v1 and v2.

The code of the website is the [phpmetrics/website](https://github.com/phpmetrics/website) repository. Do not hesitate to open Pull requests here :)
