### ISSUE TITLE
Suggestion to add more info on anonymous classes rans and other listings

### ISSUE THREAD

**Issue by brzuchal** [phpmetrics/PhpMetrics#349]
Anonymous class names on ranks like `anonymous@000000003a0028fd000000007c65dca0` give nothing useful.
I would suggest putting for eg. a filename in a tooltip which declares this class which is available through reflection.

I have installed PhpMetrics v2.3.2 with Composer.

**Comment by Halleck45** [comment]
Hi @brzuchal ,

that's a good idea ! Do you want to code this change ?

I'm not sure is that's possible (we work on nodes, not on reflected objects), but the concerned function is [getNameOfNode($node)](https://github.com/phpmetrics/PhpMetrics/blob/master/src/functions.php#L86
