### ISSUE TITLE
How get the maintainability index for a project ?

### ISSUE THREAD

**Issue by 2ur1st** [phpmetrics/PhpMetrics#350]
Hi,

I've installed PhpMetrics v2.2.0 with Docker.
I don not have a problem with PhpMetrics, but I have a question
The project does not has a actual docs and very hard to find some useful features, for example how get **the maintainability index for a project** ?

**Comment by Halleck45** [comment]
Hi @2ur1st ,

yes, documentation is old. The fastest way consists in generating an HTML report with the `--report-html` option
