### ISSUE TITLE
V2.4.0: Cyclomatic complexity calculation for a class fails 

### ISSUE THREAD

**Issue by niconoe-** [phpmetrics/PhpMetrics#359]
Hi guys,

With the release of the version 2.4.0 today, I saw that my classes have a higher cyclomatic complexity level.
This is due to the fact that methods are increasing the CCN for a class, although it shouldn't.
(See In the CyclomaticComplexityVisitor, after running the $cb lambda function).

Can you please fix this?
Thanks a lot.

Best regards,

**Comment by UFOMelkor** [comment]
Please help me understandig the problem. Are you graph the CCN over time or why is this a problem?

**Comment by niconoe-** [comment]
You can try to run PHPMetrics on a single class containing no conditions nor decision points, but 20 methods into. The CCN should be 1 but PHPMetrics will say 20.

Currently, the CCN for a class is the sum of the CCN for all its methods, which must not be the case.

**Comment by UFOMelkor** [comment]
Yes, the formula until 2.4 was `1 + Σ (cc(m_i)-1)` and has changed to `Σ (cc(m_i)`.

I could not find any way use case for calculating the CC on classes. All papers / books i consulted applied the CC to procedures / methods. The only way to apply it to classes is the Weighted Method Count with the CC as weight metric, which is `Σ (cc(m_i)`.

But perhaps it's better to add the WMC as own metric and drop the ccn for classes in a major release?
Or if you have any any sources for calculating CC for classes I would really appreciate it.

**Comment by niconoe-** [comment]
I agree about the use cases on CC Classes, I also found only references on CC for functions/methods.
But the PHPMetrics bubble graph displays all classes with the maintainability index for color and CC of the class for size, giving it much value.

Perhaps another metric should be used in the PHPMetrics bubble graph in a major release, but for now, we should keep using the ccn for classes for this graph and create the WMC as its own metric, like you purposed.

Thanks a lot.

**Comment by niconoe-** [comment]
Another way to define a cyclomatic complexity for a class could be the average of the CCN for all methods.
This way, having 3 methods with CC = 2 and 4 methods with CC = 1, you would have a CC_Class = (3*2 + 4*1) / (3+4) = 1.42857

It also offers consistancy with the average CC project displayed in the HTML output, as the average CC_Classes must be the average CC_Project

**Comment by UFOMelkor** [comment]
Average CCN sounds interesting too, but would also need a rebalance of the bublbe graph because of another value range.

Please have a look at #362 
I've re-added the old ccn by class and added the wmc as own metric. Does it look good for you?

**Comment by niconoe-** [comment]
I understand about rebalancing the bubble graph. 
I looked at #362 and it looks good to me.

Thanks again.
