### ISSUE TITLE
PHP Parse error since 2.4.0 version with PHP5.6

### ISSUE THREAD

**Issue by Angel94** [phpmetrics/PhpMetrics#360]
Hi,

I'm having a PHP parse error with lines below since the update to 2.4 version of phpmetrics.
I run it under php 5.6 which is allowed from composer.json but it seems there is a syntax error. The `php7 typehint` can't be parsed correctly.

https://github.com/phpmetrics/PhpMetrics/blob/95aa9c11c1333df1d5ac4e973af35c688a29c919/src/Hal/Component/Ast/NodeTraverser.php#L110

The error :
```bash
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in vendor/phpmetrics/phpmetrics/src/Hal/Component/Ast/NodeTraverser.php on line 110
```

Thx,

Marc

**Comment by UFOMelkor** [comment]
Hi Marc,

thank you for reporting the error. I fixed it and will release a new version tomorrow.

**Comment by Angel94** [comment]
Thx for your reactivity.
