### ISSUE TITLE
How install Phpmetrics Old Version ?

### ISSUE THREAD

**Issue by Ilhamarl** [phpmetrics/PhpMetrics#363]
Hai, i have problem to get average value of MI ( Maintainability Index ) ?
I want to get value like PhpMetrics Old Version. and How to installation with old version? 
Example version 1.10 

Thanks

**Comment by niconoe-** [comment]
Hi,

To install an old version, you can use composer (package phpmetrics/phpmetrics) or the phar archive downloadable in the list of released tags here: https://github.com/phpmetrics/PhpMetrics/releases

Regards,
