### ISSUE TITLE
PHPMetrics returns empty report

### ISSUE THREAD

**Issue by DanielGwalter1999** [phpmetrics/PhpMetrics#365]
Hi,

I've installed PhpMetrics with composer in a windows 10 environment

When I run this command: 
```
phpmetrics --report-html=c:\PHP\Calc\report c:\PHP\Calc

c:\PHP\Calc contains a calcengine script used as a json service providor.

```

I get this output:

```
script runs but returns 0 and NAN in the script output then produces an empty report with composer.json not found
```

**Comment by niconoe-** [comment]
Hi @DanielGwalter1999 ,

Could you please try it with the new version of PhpMetrics?

Also, does your project contains OOP objects like namespaces, packages and classes? If not, you won't have any results with PhpMetrics.
