### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by tvbeek** [phpmetrics/PhpMetrics#378]
Hello,

I was referring to this great package (thanks for creating and maintaining it), and I found out that phpmetrics.org is down.

I'm not sure if you are aware and / or need some help to get it up.

**Comment by davidsivocha** [comment]
Given that the package had it's last update last year, and now the website and associated documentation is down, it's starting to smell like this package has been abandoned. Which would be such a shame as it's a great static analysis tool.

**Comment by gmponos** [comment]
True.. I would really be interested in maintaining this package.

**Comment by NavyCoat** [comment]
I love this package, it will be great to help. 

Maybe we should fork it, and best fork will be chosen like sampart does with [Pagerfanta](https://github.com/whiteoctober/Pagerfanta)? How do you see future of this package? @fonsecas72 @UFOMelkor

**Comment by alnutile** [comment]
site back up! Thanks

**Comment by tvbeek** [comment]
🎉 I close this issue because the site is up 😃
