### ISSUE TITLE
spelling fix: responsability -> responsibility

### ISSUE THREAD

**Issue by rcampbel3** [phpmetrics/PhpMetrics#380]
Hi! Great tool - ran across this spelling error in the reports

https://github.com/phpmetrics/PhpMetrics/blob/cc925d2c2187610294d0defc50a623b70e0ebc2d/src/Hal/Violation/Class_/Blob.php#L63

responsability -> responsibility

Thanks!

**Comment by gmponos** [comment]
Fixed in https://github.com/phpmetrics/PhpMetrics/commit/c3dc28d3dba5d2a15f1aae2ca30087d70c3048c9
