### ISSUE TITLE
PSR-0 namespace issue for `NodeTraverser`

### ISSUE THREAD

**Issue by SunMar** [phpmetrics/PhpMetrics#382]
Hi,

As for the latest snapshot of composer when you try to generate optimised autoload files you get the following deprecation warning:

```
Deprecation Notice: Class Hal\Component\Ast\Traverser located in ./vendor/phpmetrics/phpmetrics/src/Hal/Component/Ast/NodeTraverser.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v1.11+.
```

I tried a quick fix via #381 but it looks like because of the class aliasing that doesn't work. So I'm not sure what then the best approach would be to resolving this.
https://github.com/phpmetrics/PhpMetrics/blob/8bde8f610484a90079d1ecbbc3bb5ed5fdfc699e/src/Hal/Component/Ast/Traverser.php#L98-L102

**Comment by gmponos** [comment]
I think this is fixed with #384
