### ISSUE TITLE
Download SVG image of Maintenability?

### ISSUE THREAD

**Issue by saiftheboss7** [phpmetrics/PhpMetrics#397]
Hi,

Using PHP metrics version 2.4.1. 

I can generate reports with the command. And works really well. I was just wondering if I can download the maintainability image? In previous versions (saw some screenshots) it was possible. But can't seem to find the option to download the Maintainability (complexity) image.

**Comment by Halleck45** [comment]
Hi,

the button will appear in next tag (in few days). Thanks for the report :)
