### ISSUE TITLE
Phar file not found in Jenkins Docs

### ISSUE THREAD

**Issue by siemendev** [phpmetrics/PhpMetrics#410]
Hi there,
I just ran into a faulty documentation here: https://www.phpmetrics.org/documentation/jenkins.html

The phar link you provide seems to be from a different repository (may be the former developers repo instead of the project repo).

It should be changed to https://github.com/phpmetrics/PhpMetrics/releases/download/v2.5.0/phpmetrics.phar or some more generic link.

**Comment by Halleck45** [comment]
Yes, you're right. That's fixed, site will update soin. Thanks !
