### ISSUE TITLE
DX: Explain the Google Page Rank metric

### ISSUE THREAD

**Issue by staabm** [phpmetrics/PhpMetrics#416]
first let me say, thanks for the great tool!

the home-screen of the report shows me classes sorted by google page rank

![grafik](https://user-images.githubusercontent.com/120441/77623473-71705a00-6f40-11ea-8e3b-eab2e5c8b340.png)

it would be great to have a few explaining words in this area. something along the lines:
- what is the class-rank is trying to tell me?
  - lower is better (?)
- what is a maintainability index?
  - highter is better (?)
- which facts are taken into consideration for this table - so, how to improve my scores - is it about class relations? properties? complexity?

I dont know what the table is trying to tell me, so the above suggestions might not be correct as far as the metric is concerned. please take them as a example

**Comment by staabm** [comment]
for reference, the "Maintainability / Complexity" visualization is doing a great job in explaining what is shown and what the impact is

![grafik](https://user-images.githubusercontent.com/120441/77624036-7bdf2380-6f41-11ea-959f-d220ad27a1ce.png)

**Comment by Halleck45** [comment]
Thanks for your help @staabm ! Feedbacks are really very welcome. I hope that's better now with #420
