### ISSUE TITLE
DX: Explain colors in "Composer dependencies"

### ISSUE THREAD

**Issue by staabm** [phpmetrics/PhpMetrics#417]
when looking at "Composer dependencies", some dependencies have a different color then others

![grafik](https://user-images.githubusercontent.com/120441/77623873-315da700-6f41-11ea-9a99-c5387ca27da1.png)

would be great the UI would explain to me why `firebase/php-jwt` is in red font? what does the UI try to tell me?

**Comment by Halleck45** [comment]
Hi,

thanks for your help ! 

Colors in this report are probably a bad thing : we tryied to indicates when package is outdated, but this is probably the bad way to do it (because we only use composer.lock, instead of requesting packagist.org)

I've removed colors in the composer report.

**Comment by Halleck45** [comment]
Hi,

my bad, Composer report already request packagist.org.

I'll open new PR to reintroduce colors and adding some help
