### ISSUE TITLE
Enable use as a Composer dependency

### ISSUE THREAD

**Issue by anroots** [phpmetrics/PhpMetrics#42]
Currently, when including the project via Composer as a dependency, it isn't possible to run it: including the Composer autoloader from `bin/metrics.php` fails, since it is assumed that the project is a root-level project, with its own vendor directory.

To solve that, the following changes would be necessary:
- Tell Composer to move the metrics.php to the Composer vendor/bin dir (optionally, losing the .php extension)
- Rewrite the Composer autoloader inclusion in `metrics.php` so it would work when the project is included as a dependency

If you'd like, I could try creating a pull request for this.

**Comment by jmauerhan** [comment]
I'm still having issues related to these. There is no stable version in packagist: Could not find package 'halleck45/phpmetrics' at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

And when I installed with `@dev`, I get nothing in bin, I can't figure out how to run the tool.

**Comment by Halleck45** [comment]
@jmauerhan The easiest way to run this tool consists in download the [latest phar](https://github.com/Halleck45/PhpMetrics/raw/master/build/phpmetrics.phar)

**Comment by UFOMelkor** [comment]
@jmauerhan I cannot reproduce this :(
Here it works great with `minimum-stability: stable` and with/without `@dev`.
