### ISSUE TITLE
Bug in HTML report layout

### ISSUE THREAD

**Issue by pattisahusiwa** [phpmetrics/PhpMetrics#425]
# Bug report

PhpMetrics version: 2.6.0

Should add top margin in page content.
![phpmetrics](https://user-images.githubusercontent.com/11484016/78189612-52784780-74ad-11ea-88a0-8ab7de63431b.png)

**Comment by Halleck45** [comment]
Hi,

Thanks for the report ! It will be fixed when #421 will be merged :)

**Comment by pattisahusiwa** [comment]
Confirmed. However, there are several issues on the new layout. I can fix it. What do you think?
