### ISSUE TITLE
Bug on new phpmetrics.phar  - v2.6.0

### ISSUE THREAD

**Issue by pierre-vassoilles** [phpmetrics/PhpMetrics#426]
# Bug report
I'm using phpmetrics.phar, version 2.6.0 foundable [there](https://github.com/phpmetrics/PhpMetrics/releases/tag/v2.6.0)

The new version of phpmetrics introduced a constant named PROJECT_DIR which is defined in the executable file (bin/phpmetrics) but it seems not to be defined in the phar executable. [@see build.php](https://github.com/phpmetrics/PhpMetrics/blob/v2.6.0/artifacts/phar/build.php).

Here is my error : 
`Warning: Use of undefined constant PROJECT_DIR - assumed 'PROJECT_DIR' (this will throw an Error in a future version of PHP) in phar:///tools/phpmetrics/src/Hal/Report/Html/Reporter.php on line 68`

Adding the line `define('PROJECT_DIR', dirname(__DIR__));` in the phar build script should resolve it.

**Comment by Halleck45** [comment]
Hi,

Sorry for the issue :(

[v2.6.1](https://github.com/phpmetrics/PhpMetrics/releases/tag/v2.6.1) fixes the problem

Thanks for the report. I close this issue.

**Comment by jakzal** [comment]
@Halleck45 is it possible to publish a new phar?

**Comment by Halleck45** [comment]
@jakzal in the release list ?

If yes, #427 is fixed.

**Comment by pierre-vassoilles** [comment]
Thanks for the bugfix :wink:
