### ISSUE TITLE
phar is no longer published

### ISSUE THREAD

**Issue by jakzal** [phpmetrics/PhpMetrics#427]
Last two releases do not have the phar published.

**Comment by Halleck45** [comment]
Hi,

you're right ! That's fixed:

+ https://github.com/phpmetrics/PhpMetrics/releases/tag/v2.6.2
+ https://github.com/phpmetrics/PhpMetrics/releases/tag/v2.6.1

Sorry !

**Comment by Potherca** [comment]
Looks like its broken again for https://github.com/phpmetrics/PhpMetrics/releases/tag/v2.7.4

![image](https://user-images.githubusercontent.com/195757/125072094-6bad7200-e0ba-11eb-97e8-d2e022a80feb.png)
