### ISSUE TITLE
Bug when generating html report

### ISSUE THREAD

**Issue by pattisahusiwa** [phpmetrics/PhpMetrics#429]
# Bug report

 

PhpMetrics version: 2.7.0

There is an error when generating HTML report.
````
PHP Notice:  Undefined variable: outDir in /Hal/Report/Html/Reporter.php on line 183
PHP Warning:  file_put_contents(/classes.js): failed to open stream: Permission denied in /src/Hal/Report/Html/Reporter.php on line 184
````

**Comment by Halleck45** [comment]
Hi, I reopen issue :  #430 introduced many bugs and has been reverted.

**Comment by pattisahusiwa** [comment]
I see. You put the lines inside for each. It's different from old code.
