### ISSUE TITLE
Chart is broken in group tab

### ISSUE THREAD

**Issue by Halleck45** [phpmetrics/PhpMetrics#433]
In 2.7.3, MI chart does not display due to https://github.com/phpmetrics/PhpMetrics/pull/430

We need to revert this PR

**Comment by niconoe-** [comment]
This is mainly because the js variable "classes" is redefined, IMO. Why not declaring, and using, a different variable for layer groups?

**Comment by pattisahusiwa** [comment]
@Halleck45, can you show a picture about the broken chart? or give more explanation about that. I can't reproduce the bug.

**Comment by Halleck45** [comment]
Hi @pattisahusiwa . When you click on the tab of specific group, the maintainability chart does not load due to JavaScript issue.

I think that #429 fixes the issue
