### ISSUE TITLE
Debian package is wrong on release page

### ISSUE THREAD

**Issue by Mte90** [phpmetrics/PhpMetrics#436]
# Bug report
<s>Looking at the readme the ini format is nmot supported anymore, so I migrated to the json version but also if I pass a broken JSON there are no errors about it.
Using the `help` parameter I saw that `config` parameter is not available but the readme specify it.</s>

Check https://github.com/phpmetrics/PhpMetrics/issues/436#issuecomment-652274498

**Comment by pattisahusiwa** [comment]
Yes, you can pass config file as `--config=config.json`.

**Comment by Halleck45** [comment]
What is your version of PhpMetrics ?

the ini file is always supported.

If you run `phpmetrics --help`, do you see this output ?

```
Usage:

    phpmetrics [...options...] <directories>

Required:

    <directories>                     List of directories to parse, separated by a comma (,)

Optional:

    --config=<file>                   Use a file for configuration
  
(...)
```

**Comment by Mte90** [comment]
Seems that the debian package generated in the release include a phpmetrics 1.9.2 version on https://github.com/phpmetrics/PhpMetrics/releases/tag/v2.7.3
The file in https://github.com/phpmetrics/PhpMetrics/blob/master/releases/ in fact all the files on refer to that version 1.9.2
But I don't understand why an old version (with that folder) can be used for the releases page, looking at the scripts on artifact folder they are all referring to the the right path.
