### ISSUE TITLE
JUnit config parameter docs don't match what the code actually does

### ISSUE THREAD

**Issue by AlexHowansky** [phpmetrics/PhpMetrics#441]
# Bug report

## Version 2.7.4

The `README.md` file includes this configuration file example of linking to a JUnit report:

```JSON
"junit": {
    "file": "/tmp/junit.xml"
}
```

However, the code in `Hal\Application\Config\File\ConfigFileReaderJson` uses the key `report` and not the key `file`:

```PHP
if (isset($jsonData['plugins'], $jsonData['plugins']['junit'], $jsonData['plugins']['junit']["report"])) {
```

Thus, either the `README.md` should be changed to:

```JSON
"junit": {
    "report": "/tmp/junit.xml"
}
```

Or the `Hal\Application\Config\File\ConfigFileReaderJson` should be changed to:

```PHP
if (isset($jsonData['plugins'], $jsonData['plugins']['junit'], $jsonData['plugins']['junit']["file"])) {
```

I did not create a pull request for this change as I don't know which of these two keys was intended and it's trivial enough to implement.

**Comment by Halleck45** [comment]
Thanks for the report. This will be fixed with https://github.com/phpmetrics/PhpMetrics/pull/457
