### ISSUE TITLE
Show cyclomatic complexity of methods

### ISSUE THREAD

**Issue by Mte90** [phpmetrics/PhpMetrics#444]
# Feature request

Right now the tool show the total of the class of cyclomatic complexity but maybe there are some methods that require more than the other.

**Comment by kudashevs** [comment]
The PR #481 adds the possibility to see the cyclomatic complexity of all of the methods in file.

**Comment by niconoe-** [comment]
Based on @kudashevs's work, this is now available in v3.0.0rc4. Closing.
