### ISSUE TITLE
use of bubble graph on overview page is hampered by animation

### ISSUE THREAD

**Issue by MarkProDev** [phpmetrics/PhpMetrics#451]
# Bug report

 

This is an easy one.  It would be nice to use the overview to see problem modules graphically but the animation moves the graph making it difficult to identify the problem 'children'.  Either disable the animation if a user clicks on one of the images or mouses over the image or offer another view, i.e. side by side.  I am using version 2.7.4

**Comment by Halleck45** [comment]
Hi,

I'm agree. What do you think about https://github.com/phpmetrics/PhpMetrics/pull/455 ?

Now you must click to toggle between these charts

![Capture d’écran du 2021-06-06 22-46-09](https://user-images.githubusercontent.com/1076296/120939595-0d871b00-c719-11eb-98e6-cf4570386e25.png)

**Comment by MarkProDev** [comment]
sounds great!  thank you!!!
