### ISSUE TITLE
help me solve this, i used codeigniter4 framework

### ISSUE THREAD

**Issue by yusufsenna** [phpmetrics/PhpMetrics#453]
`$ phpmetrics --report-html=C:/xampp/htdocs/spmi/HTML-REPORT/myreport.html C:/xampp/htdocs/spmi`
`Executing system analyzes...`

`Executing composer analyzes, requesting https://packagist.org...PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(./\AppData\Local\ElevatedDiagnostics,./\AppData\Local\ElevatedDiagnostics): Access is denied. (code: 5) in C:\Users\win 10\AppData\Roaming\Composer\vendor\phpmetrics\phpmetrics\src\Hal\Component\File\Finder.php:88`
`Stack trace:`
`#0 [internal function]: RecursiveDirectoryIterator->__construct('./\\AppData\\Loca...', 0)`
`#1 [internal function]: RecursiveDirectoryIterator->getChildren()`
`#2 C:\Users\win 10\AppData\Roaming\Composer\vendor\phpmetrics\phpmetrics\src\Hal\Component\File\Finder.php(88): FilterIterator->next()`
`#3 C:\Users\win 10\AppData\Roaming\Composer\vendor\phpmetrics\phpmetrics\src\Hal\Metric\System\Packages\Composer\Composer.php(76): Hal\Component\File\Finder->fetch(Array)`
`#4 C:\Users\win 10\AppData\Roaming\Composer\vendor\phpmetrics\phpmetrics\src\Hal\Metric\System\Packages\Composer\Composer.php(39): Hal\Metric\System\Packages\Composer\Composer->getComposerJsonRequirements()`
`#5 C:\Users\win 10\AppData\Roaming\Composer\vendor\p in C:\Users\win 10\AppData\Roaming\Composer\vendor\phpmetrics\phpmetrics\src\Hal\Component\File\Finder.php on line 88`

`Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(./\AppData\Local\ElevatedDiagnostics,./\AppData\Local\ElevatedDiagnostics): Access is denied. (code: 5) in C:\Users\win 10\AppData\Roaming\Composer\vendor\phpmetrics\phpmetrics\src\Hal\Component\File\Finder.php:88`
`Stack trace:`
`#0 [internal function]: RecursiveDirectoryIterator->__construct('./\\AppData\\Loca...', 0)`
`#1 [internal function]: RecursiveDirectoryIterator->getChildren()`
`#2 C:\Users\win 10\AppData\Roaming\Composer\vendor\phpmetrics\phpmetrics\src\Hal\Component\File\Finder.php(88): FilterIterator->next()`
`#3 C:\Users\win 10\AppData\Roaming\Composer\vendor\phpmetrics\phpmetrics\src\Hal\Metric\System\Packages\Composer\Composer.php(76): Hal\Component\File\Finder->fetch(Array)`
`#4 C:\Users\win 10\AppData\Roaming\Composer\vendor\phpmetrics\phpmetrics\src\Hal\Metric\System\Packages\Composer\Composer.php(39): Hal\Metric\System\Packages\Composer\Composer->getComposerJsonRequirements()`
`#5 C:\Users\win 10\AppData\Roaming\Composer\vendor\p in C:\Users\win 10\AppData\Roaming\Composer\vendor\phpmetrics\phpmetrics\src\Hal\Component\File\Finder.php on line 88`

**Comment by Halleck45** [comment]
Hello,

you've probably no permission to read the directory you're trying to analyse.

We cannot fix this issue, you should fix your local permissions.

Thanks
