### ISSUE TITLE
Git history analyses won't work with Git worktrees

### ISSUE THREAD

**Issue by claussni** [phpmetrics/PhpMetrics#461]
# Bug report

**PhpMetrics v2.7.4**

Running `phpmetrics` with the `--git` option will not work inside separated  git worktree directories. It will discover the git directory from a .git file as something like "/home/user/project/.git/worktrees/project-worktree" and fail to analyze it.

```
Executing system analyzes...fatal: not a git repository: /home/user/project/.git/worktrees/project-worktree
```

* https://git-scm.com/docs/git-worktree

**Comment by niconoe-** [comment]
Hi @claussni 

The `--git` option will be removed in PhpMetrics v3 as it offer no useful information about metrics of a project. If you need to buid Git statistics on your repository, I suggest you to use https://github.com/ejwa/gitinspector instead.

Thanks a lot for using PhpMetrics :slightly_smiling_face:
