### ISSUE TITLE
Round "Average cyclomatic complexity by class" number

### ISSUE THREAD

**Issue by gemal** [phpmetrics/PhpMetrics#469]
![image](https://user-images.githubusercontent.com/69105/158980104-adb5f48e-c814-4226-b906-7560975c4b6f.png)

the long number overflows the text making it impossible to see

Using version PHPMetrics v2.7.4

**Comment by gemal** [comment]
do you accept pull requests?

**Comment by gemal** [comment]
@Halleck45 do you accept pull requests? and will they be merged into a new release?

**Comment by niconoe-** [comment]
@gemal The v3.0.0rc1 has just been released. Please give it a try and share your feedback regarding this issue, as it should now be solved.

Thanks a lot!

**Comment by niconoe-** [comment]
Fixed since v3.0.0rc1. Closing
