### ISSUE TITLE
Please add assets to latest tag (v2.8.0)

### ISSUE THREAD

**Issue by MarcelBolten** [phpmetrics/PhpMetrics#473]
Hi @Halleck45,

Thanks for the great work!

The [latest release, 2.8.0](https://github.com/phpmetrics/PhpMetrics/releases/tag/untagged-afe7d49428e47cc9bac6) is unfortunately untagged but has the phpmetrics.phar asset and the [latest tag](https://github.com/phpmetrics/PhpMetrics/releases/tag/v2.8.0) comes unfortunately without the asset.
It would be great if phpmetrics.phar could be added to the latest tag.
My use case is that I programmatically download phpmetrics.phar via the generic url `https://github.com/phpmetrics/PhpMetrics/releases/download/PHP_METRICS_VERSION/phpmetrics.phar` which obviously does not work currently.

**Comment by MarcelBolten** [comment]
Of course I could also use another url provided by github `https://github.com/phpmetrics/PhpMetrics/raw/v2.8.0/releases/phpmetrics.phar` so don't worry to much about this request.

**Comment by Halleck45** [comment]
Hi,

Thanks for the report !

Is it ok now ?

**Comment by MarcelBolten** [comment]
Yes, perfect.
Thanks for the very fast response.
