### ISSUE TITLE
artifacts/phar has phpmetrics.deb?raw=true

### ISSUE THREAD

**Issue by gemal** [phpmetrics/PhpMetrics#482]
![image](https://user-images.githubusercontent.com/69105/202645638-b808e596-d84c-4010-bd7b-084da10570a6.png)

this looks wrong and produces a problem when trying to clone a forked repo

![image](https://user-images.githubusercontent.com/69105/202645849-3316e328-536d-45e1-b8e7-94bd63520fac.png)

**Comment by gemal** [comment]
it makes it impossible to clone your repo :(

**Comment by niconoe-** [comment]
Hi @gemal 
Sorry for the disturbance, the 2 artefacts files `phpmetrics.deb?raw=true` and `toto.eb` are now removed. You should be able to clone the repo.
