### ISSUE TITLE
page has invalid html

### ISSUE THREAD

**Issue by gemal** [phpmetrics/PhpMetrics#483]
PHPMetrics v2.8.1

wrong tag is closed so span is not closed and then td is closed 2 times:

![image](https://user-images.githubusercontent.com/69105/202649052-4467c3de-fe5f-4b29-925a-d5af578827a4.png)

**Comment by niconoe-** [comment]
Hi @gemal 

This is fixed in the incoming v3 of PhpMetrics. If you want this to be fixed on the version 2.8, please provide a PR.

Thanks a lot for using PhpMetrics :slightly_smiling_face:

**Comment by gemal** [comment]
> Hi @gemal
> 
> This is fixed in the incoming v3 of PhpMetrics. If you want this to be fixed on the version 2.8, please provide a PR.
> 

Cool. When do you expect v3 to become available? And what features will be included?

**Comment by niconoe-** [comment]
I'm trying to spend some time on v3, but that's a long road. Major changes will be:
* PHP 8.1 and PHP 8.2 only are supported
* Installation and usage only via composer
* Remove PHPUnit coverage and Git metrics (some dedicated tools are more powerful)
* Lots of new PHP tokens taken into account to better manage Objects and Packages metrics.

There's no due date for v3 unfortunately, but I will probably provide a beta version soon as I have troubles to test a lot of different kind of projects, and having users feedback could help a lot.

**Comment by gemal** [comment]
can you make a 2.8.2 release since this is already fixes on master?

**Comment by niconoe-** [comment]
This is not fixed on master. master is currently on the same status than version 2.8.1 + very minor stuff, but not this fix.

**Comment by gemal** [comment]
I'm pretty sure this one is already fixed on master
https://github.com/phpmetrics/PhpMetrics/blob/master/templates/html_report/index.php#L150

**Comment by niconoe-** [comment]
@gemal The v3.0.0rc1 has just been released. Please give it a try and share your feedback regarding this issue, as it should now be solved.

Thanks a lot!

**Comment by niconoe-** [comment]
Fixed since v3.0.0rc1. Closing
