### ISSUE TITLE
Formula

### ISSUE THREAD

**Issue by mutiaramahee** [phpmetrics/PhpMetrics#492]
Hello!
I found a different formula from the PhpMetrics result with the formula in the documentation.
I need to explain Maintenance Index formula (MIwoc) used in PhpMetrics in my thesis. But I'm confused and have no clue.

I found the MI formula without comments (MIwoc) in PhpMetrics is
Max(0, (171 - 5.2 * ln(V) - 0.23 * (G) - 16.2 * ln(LLOC)) * 100 / 171)

While the MIwoc formula on the web documentation is
171 - 5.2 * ln(aveV) - 0.23 * aveG - 16.2 * ln(aveLOC)

I feel that I am not very good at it, so I will be very happy and helpful if someone wants to explain it to me. I almost felt hopeless because I was confused about who to ask. 
Thank You :)

* I tried to calculate manually using a spreadsheet, I took each value of the elements in the formula from the measurement results generated by PhpMetrics -- Halstead volume (V), Cyclomatic Complexity (G), and line count without empty lines (LLOC).

**Comment by niconoe-** [comment]
Hi and thank you for your message.

Indeed, the formula was updated a little bit from its original definition. The issue with the original formula is that its range is from 171 to an unbounded negative number, which is therefore sometimes impossible to represent in graphs, or to use in other formulas. Also, when too much negative, it becomes irrelevant as the scale is logarithmic.

We decided, to solve those related issues, to migrate the range to from 1 to 171, which is just another mathematical representation which suits better to our needs and solve those constraints.

For instance, Microsoft did exactly the same for Visual Studio, probably to solve the same issues we got : https://learn.microsoft.com/en-us/visualstudio/code-quality/code-metrics-maintainability-index-range-and-meaning?view=vs-2022

So, don’t worry, both formulas are correct, they are just not being represented on the same range 😉.

**Comment by mutiaramahee** [comment]
Aaa.. thank you very much!
I quite understand. Please allow me to ask again.
If indeed MIwoc uses the formula Max(0, (171 - 5.2 * ln(V) - 0.23 * (G) - 16.2 * ln(LLOC)) * 100 / 171), 
does the MI value (MIwoc + MIcw) still have a categorization like the image below?
![photo_6282588920214567211_y](https://github.com/phpmetrics/PhpMetrics/assets/39557008/c1390f0b-2cb1-448f-a7f1-e9ae942894e9)

**Comment by niconoe-** [comment]
It should have it, yes. I’ll double check this and I’ll tell you when available.

**Comment by mutiaramahee** [comment]
Thank you.. I hope to hear from you soon.

**Comment by niconoe-** [comment]
After a small analysis, you actually pointed something out. 
Looking at the incoming [version 3 source code](https://github.com/phpmetrics/PhpMetrics/blob/3.x-dev/src/Hal/Metric/Class_/Component/MaintainabilityIndexVisitor.php) you can see that the scale modification is applied **before** the addition with the MIwc. Therefore, the formula currently used is wrong, as it mixes different scales.

I'll fix that very soon to make it correct.

About the boundaries you displayed (<64, 65-84, >85), they are correct and must remain correct regarding the 171 to 0 scale MI must use. Those values are because they represent approx. 37.5% (for 64) and 50% (for 85) of the maximum theoric maintainability index value (171).
It appears to also be a set of boundaries used by other programs looking at code quality in orther languages (C++ and Java, for instance: https://verifysoft.com/en_maintainability.html)

I'll try to fix the scale rearrangement soon. Thanks for spotting this out!

**Comment by mutiaramahee** [comment]
Thank you for doing the analysis regarding my question. And I'm glad what I found can help you improve PhpMetrics  (*^◇^)/

I hope you can provide more info here soon. And it would probably be great if you could update the documentation too!

**Comment by ichsnn** [comment]
![image](https://github.com/user-attachments/assets/215ca442-df49-4b47-8843-ef24f23988e5)

[templates/html_report/js/graph-maintainability.js](https://github.com/phpmetrics/PhpMetrics/blob/10f099e1dd0f45def6e511fd91809e0719f16f11/templates/html_report/js/graph-maintainability.js#L51)

@niconoe-  I'm still curious about the maintainability index range. Why, in the code I found, does the range of the index you explained not match what is in the code? In the code, the range for without comments is: green > 65; yellow > 53; and red if less than that. Whereas with comments, the yellow range starts from > 69, not from 65 as you mentioned.

> About the boundaries you displayed (<64, 65-84, >85), they are correct and must remain correct regarding the 171 to 0 scale MI must use. Those values are because they represent approx. 37.5% (for 64) and 50% (for 85) of the maximum theoric maintainability index value (171).

Are there any valid articles or journals that explain the maintainability index range used as a reference by PhpMetrics?
