### ISSUE TITLE
Cyclomatic complexity as distribution and overall volume calculation

### ISSUE THREAD

**Issue by sydekumf** [phpmetrics/PhpMetrics#493]
# Feature request

I was looking into this awesome reporting tool and was questioning myself the following: Why isn't the overall volume of a whole program being calculated as an indicator of the program's volume/size/dimension?

I just see average volume per class, but the overall volume would be a good indication for comparisons. Do you agree or do I see it wrong?

Another cool feature would a distribution diagram of all the cyclomatic complexities of all the classes and to define a threshold which indicates as a red line in this distribution diagram.

**Comment by niconoe-** [comment]
I agree with Halstead volume, and maybe other metrics could be added at project level too.

I'm not sure I'm understanding what do you expect as a distribution diagram for the CC. Usually, diagram distributions are covering data through a Bell curve. As ideal CC by class is 1, and it's the minimum, the Bell Curve will only decrease on the right side of the diagram, which would fail in trying to determine a red line.
Or maybe I don't understand your point, so do you have a graph example in mind?

**Comment by niconoe-** [comment]
Closing as no answer from OP.
