### ISSUE TITLE
Prepare for newer PHP versions

### ISSUE THREAD

**Issue by MetalArend** [phpmetrics/PhpMetrics#508]
# Bug report

Running PhpMetrics against the newest PHP versions (PHP 8.3) gives a lot of deprecation warnings:

- Creation of dynamic property xxx is deprecated
- Deprecated: abs(): Passing null to parameter #1 ($num) of type int|float is deprecated
- Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated

**Comment by niconoe-** [comment]
Fixed on v3 (rc6).
