### ISSUE TITLE
A Default Ruleset 

### ISSUE THREAD

**Issue by fonsecas72** [phpmetrics/PhpMetrics#99]
When I use a config file I have to set every single ruleset in my config for this tool to work properly.

Doing this causes me some trouble:
* I don't know which values to use
* I don't know each ruleset's name
 
At RuleSet class __contructor we have an array that suggests a default list of ruleset and I can use that to config the yml properly.

Obviously, this is not something as easy as it should be.
Perhaps this ruleset list should in fact be a default list and then we would merge this at the __contructor.

This seems obvious to me but as there are tests that will fail, I rather ask you first instead of PR right away.

**Comment by Halleck45** [comment]
Yes, ruleset definition could be injected with another object / config file, in order to centralize definitions and reuse them everywhere.

**Comment by Halleck45** [comment]
@fonsecas72 what do you think about #207 ?

**Comment by Halleck45** [comment]
Fixed by #207 . I close this issue
